/**
 * CDX005 S3 Mechanical Split - Round-Trip Contract (local only, no browser).
 *
 * Every boundary is re-derived independently from the frozen authority
 * original with byte search and this file's own logic, then compared against
 * the materialized split. Nothing is taken on trust from materialization.json.
 *
 * CDX005 is a STANDALONE_AUTHORITY_SURFACE capsule (S1 authority accepted at
 * workdiary ca5e756; S2 baseline accepted at issue #589 comment 5887518417).
 * Its 80 runtime turn-around PNGs are generated by one relative template inside
 * the authority and resolve against the authority's own folder, so they are
 * vendored byte-exact under original/assets/ and split/assets/ with ZERO url
 * rewrites and both repository surfaces are runtime surfaces.
 *
 * The frozen source is pixel-nondeterministic by authored design (D1-D5).
 * This file asserts NOTHING about pixels, screenshots or parity equality. It
 * asserts only byte identity of the mechanical split and preservation of the
 * frozen defects.
 *
 * S4 is NOT started and NOT claimed by this file.
 *
 * Proves:
 *  - T01/T02  frozen authority byte identity (SHA-256 + size, untouched)
 *  - T03/T03b frozen input layout + manifest authority lock
 *  - T04      source block inventory: exactly 1 style + 1 bare script,
 *             zero attributed/external script tags, zero external link tags,
 *             zero real external network dependencies
 *  - T05/T06  styles.css / script.js are the exact authority block inners
 *  - T07      split shell carries exactly the two mechanical glue refs and
 *             zero inline style / zero inline script body
 *  - T08      materialization boundary metadata matches independent re-derivation
 *  - T09      reconstructed HTML is byte-identical to the frozen authority
 *  - T10/T11  CSS/JS semantics preserved (byte-exact) and DOM order is a pure
 *             positional splice
 *  - T12      no React/TS/TSX/JSX/Next/backend/DB/auth markers
 *  - T13      the authored asset template is preserved byte-identically, the
 *             derived 80-path set equals the vendored set, and both vendored
 *             copies match the pinned Drive digests; no re-encode, no rewrite
 *  - T14      authority-context.json records the standalone serving contract,
 *             the 80 pinned assets and the D1-D5 frozen defects
 *  - T15      materialization output hashes + git blobs match on-disk files
 *  - T16      stage flags S0-S3 complete, S4 candidate-only and fail-closed,
 *             parity never claimed, capture_surface STANDALONE_AUTHORITY_SURFACE
 *  - T17      duplicate-variant governance: SINGLE_EXECUTABLE_NO_DUPLICATE
 *             with the V1 superseded / duplicate-copy note, launcher not
 *             vendored, no Product or Lineage58 adoption
 *
 * Writes S3 run evidence to an OS temp directory only; the committed
 * evidence/s3/roundtrip.json record is never overwritten by a test run.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CAPSULE = path.resolve(HERE, "..");
const REPO_ROOT = path.resolve(HERE, "..", "..", "..", "..");
const read = (rel) => fs.readFileSync(path.join(CAPSULE, rel));
const readJson = (rel) => JSON.parse(read(rel).toString("utf8"));
const sha256 = (b) => crypto.createHash("sha256").update(b).digest("hex");
const gitBlobSha1 = (b) => crypto
  .createHash("sha1")
  .update(Buffer.concat([Buffer.from(`blob ${b.length}\0`), b]))
  .digest("hex");
const count = (text, needle) => text.split(needle).length - 1;

const AUTHORITY_BYTES = 27918;
const AUTHORITY_SHA256 = "ac30f2abfc88e99e1ce7829f270c4cc76a5eae93b5f1b1e3a56dac1654c5b466";
const AUTHORITY_DRIVE_FILE_ID = "1iC6IyJBy86UhIANts6nDm414WnBUU66p";
const LAUNCHER_DRIVE_FILE_ID = "1JlrwZGdsD1oQhzIzSrYYGcOH_Tu61J-K";
const V1_DRIVE_FILE_ID = "1DbxEQtlHuAgSfrsC_LIhKlUvWfmABkMg";
const V1_COPY_DRIVE_FILE_ID = "1eqNaaDsEKSFLIKCddee4rNGyGW6y5v15";
const CSS_LINK = '<link rel="stylesheet" href="./styles.css"/>';
const SCRIPT_SRC = '<script src="./script.js"></script>';
const ANGLES = ["000", "045", "090", "135", "180", "225", "270", "315"];
const LOOKS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"];
const FROZEN_DEFECT_IDS = ["D1", "D2", "D3", "D4", "D5"];

const originalBytes = read("original/original.html");
const original = originalBytes.toString("utf8");
const indexBytes = read("split/index.html");
const index = indexBytes.toString("utf8");
const css = read("split/styles.css").toString("utf8");
const js = read("split/script.js").toString("utf8");

// Independent re-derivation of every boundary from the frozen authority.
const styleOpen = original.indexOf("<style>");
const styleClose = original.indexOf("</style>", styleOpen + 7);
const scriptOpenCount = count(original, "<script>");
const scriptOpen = original.indexOf("<script>", styleClose + "</style>".length);
const scriptClose = original.indexOf("</script>", scriptOpen + "<script>".length);
const derivedCss = original.slice(styleOpen + "<style>".length, styleClose);
const derivedJs = original.slice(scriptOpen + "<script>".length, scriptClose);
const derivedShell = original.slice(0, styleOpen)
  + CSS_LINK
  + original.slice(styleClose + "</style>".length, scriptOpen)
  + SCRIPT_SRC
  + original.slice(scriptClose + "</script>".length);
const reconstructed = derivedShell
  .replace(CSS_LINK, () => `<style>${derivedCss}</style>`)
  .replace(SCRIPT_SRC, () => `<script>${derivedJs}</script>`);

const manifest = readJson("manifest.json");
const context = readJson("authority-context.json");
const baseline = readJson("baseline/accepted-baseline.json");
const materialization = readJson("split/materialization.json");

const listAssets = (which) => fs
  .readdirSync(path.join(CAPSULE, which, "assets", "turnarounds", "transparent"))
  .filter((n) => n.endsWith(".png"))
  .sort();
const originalAssets = listAssets("original");
const splitAssets = listAssets("split");
const assetDigest = (which, name) => sha256(read(`${which}/assets/turnarounds/transparent/${name}`));

const checks = [];
const record = (id, pass, detail) => { checks.push({ id, pass, detail }); return pass; };

test("T01/T02 frozen authority byte identity is locked and untouched", () => {
  assert.equal(record("T01", originalBytes.length === AUTHORITY_BYTES, `authority byte size ${originalBytes.length}`), true);
  assert.equal(record("T02", sha256(originalBytes) === AUTHORITY_SHA256, "authority SHA-256 locked"), true);
  assert.equal(Buffer.from(original, "utf8").compare(originalBytes), 0, "original decodes as stable UTF-8");
});

test("T03/T03b frozen layout intact and the manifest authority lock agrees", () => {
  assert.equal(record("T03", fs.existsSync(path.join(CAPSULE, "original", "assets", "turnarounds", "transparent")), "frozen original asset directory present"), true);
  assert.equal(record("T03b", manifest.authority.bytes === AUTHORITY_BYTES && manifest.authority.sha256 === AUTHORITY_SHA256, "manifest authority lock matches the frozen authority"), true);
  assert.equal(manifest.authority.drive_file_id, AUTHORITY_DRIVE_FILE_ID);
  assert.equal(manifest.authority.status, "LOCKED");
  assert.equal(manifest.codex_id, "CDX005");
  assert.equal(manifest.master_rows.includes("MST105"), true);
  assert.equal(manifest.runtime_policy, "HTML_CSS_JS_MECHANICAL_ONLY");
  assert.equal(manifest.tsx_allowed_during_split, false);
  assert.equal(manifest.mechanical_split_ref, "split/materialization.json");
  assert.equal(manifest.baseline_ref, "baseline/accepted-baseline.json");
  assert.equal(manifest.authority_context_ref, "authority-context.json");
});

test("T04 source block inventory is exactly one style and one bare inline script", () => {
  assert.equal(record("T04a", count(original, "<style>") === 1 && count(original, "</style>") === 1, "exactly one style block"), true);
  assert.equal(record("T04b", scriptOpenCount === 1 && count(original, "</script>") === 1, "exactly one bare inline script block"), true);
  assert.equal(record("T04c", count(original, "<script") === scriptOpenCount, "zero attributed or external script tags"), true);
  assert.equal(record("T04d", count(original, "<link") === 0, "zero stylesheet link tags in the authority"), true);
  const httpHits = [...original.matchAll(/https?:\/\/[^\s"'`)<>]+/g)].map((m) => m[0]);
  assert.equal(record("T04e", JSON.stringify([...new Set(httpHits)]) === JSON.stringify(["http://www.w3.org/2000/svg"]), "only the SVG XML namespace is http-shaped, and it is not a network request"), true);
  for (const primitive of ["fetch(", "XMLHttpRequest", "sendBeacon", "importScripts(", "EventSource", "new WebSocket", "wss://", "<iframe", "<video", "<audio", "@import", "@font-face"]) {
    assert.equal(record(`T04f.${primitive}`, !original.includes(primitive), `no ${primitive} in the authority`), true);
  }
  assert.equal(record("T04g", count(original, "data:image") === 1, "exactly one inline data:image URI (SVG noise texture)"), true);
});

test("T05/T06 styles.css and script.js are the exact authority block inners", () => {
  assert.equal(record("T05", Buffer.from(css, "utf8").equals(Buffer.from(derivedCss, "utf8")), "styles.css equals the authority <style> inner bytes"), true);
  assert.equal(record("T06", Buffer.from(js, "utf8").equals(Buffer.from(derivedJs, "utf8")), "script.js equals the authority <script> inner bytes"), true);
  assert.equal(record("T05b", materialization.outputs["split/styles.css"].sha256 === sha256(read("split/styles.css")), "materialization records the on-disk styles.css digest"), true);
  assert.equal(record("T06b", materialization.outputs["split/script.js"].sha256 === sha256(read("split/script.js")), "materialization records the on-disk script.js digest"), true);
});

test("T07 split shell carries exactly the two mechanical glue refs and no inline bodies", () => {
  assert.equal(record("T07a", count(index, CSS_LINK) === 1, `exactly one ${CSS_LINK}`), true);
  assert.equal(record("T07b", count(index, SCRIPT_SRC) === 1, `exactly one ${SCRIPT_SRC}`), true);
  assert.equal(record("T07c", !index.includes("<style>"), "split index carries no inline style block"), true);
  assert.equal(record("T07d", count(index, "<script>") === 0, "split index carries no inline script body"), true);
  assert.equal(record("T07e", Buffer.from(index, "utf8").equals(Buffer.from(derivedShell, "utf8")), "split index equals the independently re-derived two-glue shell"), true);
});

test("T08 materialization boundary metadata matches the independent re-derivation", () => {
  const b = materialization.boundaries;
  assert.equal(record("T08a", b.style_open === styleOpen, `style_open=${b.style_open}`), true);
  assert.equal(record("T08b", b.style_close === styleClose, `style_close=${b.style_close}`), true);
  assert.equal(record("T08c", b.script_open === scriptOpen, `script_open=${b.script_open}`), true);
  assert.equal(record("T08d", b.script_close === scriptClose, `script_close=${b.script_close}`), true);
  assert.equal(record("T08e", b.script_blocks.length === 1 && b.script_blocks[0].length === derivedJs.length, "single script block with the derived length"), true);
  assert.equal(record("T08f", JSON.stringify(b.script_gaps) === "[]", "no script gaps"), true);
  assert.equal(record("T08g", materialization.glue.css_link === CSS_LINK && materialization.glue.script_src === SCRIPT_SRC, "materialization records the exact glue strings"), true);
  assert.equal(record("T08h", materialization.generation === "MECHANICAL_INLINE_EXTRACTION", "generation is a mechanical inline extraction"), true);
});

test("T09 reconstructed authority is byte-identical to the frozen original", () => {
  const reconstructedBytes = Buffer.from(reconstructed, "utf8");
  assert.equal(record("T09a", reconstructedBytes.compare(originalBytes) === 0, "round-trip reconstruction is byte-identical"), true);
  assert.equal(record("T09b", reconstructedBytes.length === AUTHORITY_BYTES, `reconstructed byte size ${reconstructedBytes.length}`), true);
  assert.equal(record("T09c", sha256(reconstructedBytes) === AUTHORITY_SHA256, "reconstructed SHA-256 equals the authority SHA-256"), true);
  assert.equal(record("T09d", materialization.round_trip_evidence.byte_identical === true, "materialization asserts byte identity"), true);
  assert.equal(readJson("evidence/s3/roundtrip.json").round_trip_byte_identity, true);
  assert.equal(readJson("evidence/s3/roundtrip.json").round_trip_sha256, AUTHORITY_SHA256);
});

test("T10/T11 CSS and JS are byte-exact and the shell is a pure positional splice", () => {
  assert.equal(record("T10", css === derivedCss, "CSS semantics preserved byte-exact"), true);
  assert.equal(record("T11", js === derivedJs, "JS semantics preserved byte-exact"), true);
  const before = original.slice(0, styleOpen);
  const after = original.slice(scriptClose + "</script>".length);
  assert.equal(record("T11b", index.startsWith(before), "markup before the style block is untouched"), true);
  assert.equal(record("T11c", index.endsWith(after), "markup after the script block is untouched"), true);
  const midA = original.slice(styleClose + "</style>".length, scriptOpen);
  assert.equal(record("T11d", index.includes(midA), "markup between the two blocks is untouched and in order"), true);
  assert.equal(record("T11e", index.indexOf(CSS_LINK) < index.indexOf(SCRIPT_SRC), "CSS glue precedes script glue, preserving authored order"), true);
});

test("T12 no framework, TypeScript, backend, auth or DB surface was introduced", () => {
  const surface = `${index}\n${css}\n${js}`;
  for (const marker of ["import React", "from 'react'", 'from "react"', "useState", "useEffect", "createRoot", "next/", "NextPage", "next.config", "firebase", "getAuth", "signInWith", "drizzle", "neon", "DATABASE_URL", "process.env", "require(", "module.exports"]) {
    assert.equal(record(`T12.${marker}`, !surface.includes(marker), `no ${marker} in the split surface`), true);
  }
  const splitFiles = fs.readdirSync(path.join(CAPSULE, "split")).filter((n) => /\.(ts|tsx|jsx)$/i.test(n));
  assert.equal(record("T12.ext", splitFiles.length === 0, "no .ts/.tsx/.jsx file in the split surface"), true);
  assert.equal(record("T12.closure", materialization.contracts.framework_conversion === false && materialization.contracts.tsx_or_jsx_introduced === false, "materialization records no framework conversion"), true);
  assert.equal(record("T12.policy", manifest.runtime_policy === "HTML_CSS_JS_MECHANICAL_ONLY" && manifest.tsx_allowed_during_split === false, "manifest keeps the mechanical-only runtime policy"), true);
});

test("T13 the authored asset template, the derived 80-path set and both vendored copies are preserved", () => {
  const template = "const path=(id,a)=>`assets/turnarounds/transparent/${id}_${a}.png`";
  assert.equal(record("T13a", js.includes(template), "authored relative asset template survives byte-identically in script.js"), true);
  const angles = js.match(/const angles=\[[^\]]*\]/);
  assert.equal(record("T13b", angles && JSON.stringify(JSON.parse(angles[0].slice(angles[0].indexOf("[")).replace(/'/g, '"'))) === JSON.stringify(ANGLES), "authored angle table is the expected 8 values"), true);
  const ids = [...js.matchAll(/\{id:'([A-J])'/g)].map((m) => m[1]);
  assert.equal(record("T13c", JSON.stringify(ids) === JSON.stringify(LOOKS), "authored look id table is the expected 10 values"), true);
  const derived = LOOKS.flatMap((id) => ANGLES.map((a) => `${id}_${a}.png`));
  assert.equal(record("T13d", JSON.stringify(originalAssets) === JSON.stringify(derived), "original vendored set equals the derived 10x8 required path set"), true);
  assert.equal(record("T13e", JSON.stringify(splitAssets) === JSON.stringify(derived), "split vendored set equals the derived 10x8 required path set"), true);
  assert.equal(record("T13f", originalAssets.length === 80 && splitAssets.length === 80, "80 assets vendored on each side"), true);
  const pinned = new Map(context.assets.entries.map((e) => [e.path.split("/").pop(), e]));
  let mismatched = 0;
  for (const name of derived) {
    const pin = pinned.get(name);
    if (!pin) { mismatched += 1; continue; }
    if (assetDigest("original", name) !== pin.sha256) mismatched += 1;
    if (assetDigest("split", name) !== pin.sha256) mismatched += 1;
    if (!pin.drive_file_id) mismatched += 1;
  }
  assert.equal(record("T13g", mismatched === 0, "all 80 vendored files match the pinned Drive digest on both sides, each with a Drive object id"), true);
  const unrewritten = [...original.matchAll(/assets\/turnarounds\/transparent\/[A-Za-z0-9${}_\-\/\.]*/g)].map((m) => m[0]);
  assert.equal(record("T13h", unrewritten.length === 1 && unrewritten[0] === "assets/turnarounds/transparent/${id}_${a}.png", "the authored relative prefix is preserved verbatim in the authority and is not rebased"), true);
  assert.equal(record("T13i", !index.includes("..") && !index.includes("/src/"), "split index introduces no path rebasing"), true);
  assert.equal(record("T13j", materialization.contracts.asset_url_rewritten === false && materialization.contracts.asset_reencoded === false, "no asset URL rewrite and no re-encode"), true);
  assert.equal(record("T13k", context.assets.asset_url_rewrite === 0 && context.assets.asset_reencode === 0 && context.assets.asset_resize === 0, "asset policy records zero rewrite, zero re-encode, zero resize"), true);
});

test("T14 authority-context records the standalone serving contract, the pinned assets and the frozen defects", () => {
  assert.equal(record("T14a", context.capture_surface === "STANDALONE_AUTHORITY_SURFACE", "capture surface is STANDALONE_AUTHORITY_SURFACE"), true);
  assert.equal(record("T14b", context.authority_mode === "SINGLE", "authority mode is SINGLE"), true);
  assert.equal(record("T14c", context.root_to_v2_relation === "AUTHORED_REDIRECT_BOOTSTRAP_MULTI_VECTOR_SAME_TARGET", "root launcher relation recorded"), true);
  assert.equal(record("T14d", context.v1_relation === "SUPERSEDED_REVISION_NOT_AUTHORITY", "V1 relation recorded as superseded revision"), true);
  assert.equal(record("T14e", context.v1_subtree_copy_relation === "DUPLICATE_COPY_SAME_SHA_NOT_AUTHORITY", "V1 sub-tree copy relation recorded as duplicate copy"), true);
  assert.equal(record("T14f", context.parity_contract === "SOURCE_SPECIFIC_MOTION_AWARE", "parity contract recorded"), true);
  assert.equal(record("T14g", JSON.stringify(context.frozen_source_defects) === JSON.stringify(FROZEN_DEFECT_IDS), "D1-D5 recorded in order"), true);
  assert.equal(record("T14h", context.frozen_source_defects_detail.every((d) => d.repaired === false), "no frozen defect claims a repair"), true);
  const d4 = context.frozen_source_defects_detail.find((d) => d.id === "D4");
  const d5 = context.frozen_source_defects_detail.find((d) => d.id === "D5");
  assert.equal(record("T14i", d4.title.includes("#autoBtn") && d5.title.includes("non-scrollable"), "mobile D4 and D5 are recorded as preserved source facts, not fixes"), true);
  assert.equal(record("T14j", context.serving_contract.repository_path_runtime_equivalent === true && context.serving_contract.zero_rewrites === true, "serving contract is standalone and zero-rewrite"), true);
  assert.equal(record("T14k", context.serving_contract.external_network_dependency_count === 0, "no external network dependency"), true);
  assert.equal(record("T14l", context.assets.count === 80 && context.assets.hash_match === "80/80", "80 assets pinned with an 80/80 hash match"), true);
  assert.equal(record("T14m", context.assets.drive_folder_id === "169jIiX32b19gRy4Wq6SAd3TtiQfuVaW3", "asset Drive folder pinned"), true);
  assert.equal(record("T14n", context.authority.drive_file_id === AUTHORITY_DRIVE_FILE_ID, "authority Drive file id pinned"), true);
  assert.equal(record("T14o", context.root_launcher.is_authority === false && context.root_launcher.vendored_as_original === false, "root launcher is recorded as non-authority and is not vendored"), true);
  assert.equal(record("T14p", context.root_launcher.drive_file_id === LAUNCHER_DRIVE_FILE_ID && context.root_launcher.bytes === 1041, "launcher identity preserved in metadata only"), true);
  const superseded = context.superseded_revisions;
  assert.equal(record("T14q", superseded.length === 2 && superseded.every((r) => r.vendored === false), "both superseded V1 objects are recorded and neither is vendored"), true);
  assert.equal(record("T14r", superseded[0].drive_file_id === V1_DRIVE_FILE_ID && superseded[1].drive_file_id === V1_COPY_DRIVE_FILE_ID, "V1 and V1-copy Drive file ids pinned"), true);
  assert.equal(record("T14s", superseded[0].sha256 === superseded[1].sha256 && superseded[1].relation === "DUPLICATE_COPY_SAME_SHA_NOT_AUTHORITY", "the V1 pair is recorded as the same-SHA duplicate copy"), true);
  assert.equal(record("T14t", !fs.existsSync(path.join(CAPSULE, "original", "assets", "turnarounds", "transparent", "V1.png")), "no V1 object leaked into the vendored asset set"), true);
  // Guard against the transposed-character Drive id regression corrected at
  // #589 comment 5888330856: the correct V1 id ends ...WfmABkMg, not ...WmfABkMg.
  // The scan deliberately excludes this test file, which necessarily holds the
  // wrong literal as the guard constant itself.
  const V1_ID_TYPO = "1DbxEQtlHuAgSfrsC_LIhKlUvWmfABkMg";
  const scannedFiles = ["manifest.json", "authority-context.json", "split/materialization.json", "baseline/accepted-baseline.json", "evidence/s3/roundtrip.json", "original/original.html", "split/index.html", "split/styles.css", "split/script.js"];
  const capsuleText = scannedFiles.map((rel) => read(rel).toString("utf8")).join("\n");
  assert.equal(record("T14u", !capsuleText.includes(V1_ID_TYPO), "the transposed V1 Drive file id appears in none of the scanned capsule files"), true);
  assert.equal(record("T14v", V1_DRIVE_FILE_ID === "1DbxEQtlHuAgSfrsC_LIhKlUvWfmABkMg", "the pinned V1 Drive file id is the exact S1 authority value"), true);
  assert.equal(record("T14w", V1_DRIVE_FILE_ID.length === 33 && V1_COPY_DRIVE_FILE_ID.length === 33, "both V1 Drive file ids are well-formed 33-character ids"), true);
  assert.equal(record("T14x", superseded[1].duplicate_of_drive_file_id === V1_DRIVE_FILE_ID, "the derived duplicate_of_drive_file_id field carries the same corrected V1 id"), true);
  assert.equal(record("T14y", V1_DRIVE_FILE_ID !== V1_ID_TYPO, "the pinned id and the transposed id are genuinely different strings"), true);
});

test("T15 materialization output hashes and git blobs match the on-disk files", () => {
  for (const rel of ["split/index.html", "split/styles.css", "split/script.js"]) {
    const b = read(rel);
    const pin = materialization.outputs[rel];
    assert.equal(record(`T15.${rel}.bytes`, pin.bytes === b.length, `${rel} byte size`), true);
    assert.equal(record(`T15.${rel}.sha256`, pin.sha256 === sha256(b), `${rel} sha256`), true);
    assert.equal(record(`T15.${rel}.blob`, pin.git_blob_sha1 === gitBlobSha1(b), `${rel} git blob`), true);
  }
  assert.equal(record("T15.authority", materialization.authority.bytes === AUTHORITY_BYTES && materialization.authority.sha256 === AUTHORITY_SHA256, "materialization authority lock"), true);
  assert.equal(record("T15.status", materialization.status === "MATERIALIZED_PENDING_PARITY", "materialization is pending parity, not accepted"), true);
});

test("T16 stage flags S0-S3 complete, S4 candidate-only and fail-closed, parity never claimed", () => {
  /* Lifecycle-aware (HOLD-3). The S3-era assertion "no evidence/s4 directory exists" is now
   * legitimately false, because CENTRAL released S4 for CANDIDATE capture. The guard is NOT
   * deleted: it is strengthened into a two-branch invariant that still fails closed.
   *
   *   no evidence/s4            -> S4 is unreleased, capture unauthorized, parity NOT_STARTED
   *   evidence/s4 exists        -> S4 is RELEASED_CANDIDATE_ONLY, capture authorized, parity
   *                               CANDIDATE_PENDING_CENTRAL, and NOTHING is promoted
   *
   * In BOTH branches parity is never claimed: no accepted-parity.json, no parity_ref, and
   * source_split_parity_pass stays false. A stale HOLD_CENTRAL alongside an existing evidence/s4
   * is exactly the inconsistency HOLD-2 reported, and is rejected here. */
  const s = manifest.stages;
  const s4Exists = fs.existsSync(path.join(CAPSULE, "evidence", "s4"));
  const acceptedParity = path.join(CAPSULE, "evidence", "parity", "accepted-parity.json");

  assert.equal(record("T16a", s.identity_verified === true && s.raw_authority_locked === true, "S0 and S1 complete"), true);
  assert.equal(record("T16b", s.baseline_captured === true, "S2 baseline captured"), true);
  assert.equal(record("T16c", s.mechanical_split_complete === true, "S3 mechanical split complete"), true);
  assert.equal(record("T16d", s.source_split_parity_pass === false, "S4 parity NOT passed"), true);

  if (!s4Exists) {
    assert.equal(record("T16e", context.stage_gate.s4_release === "HOLD_CENTRAL", "S4 unreleased: release is HOLD_CENTRAL"), true);
    assert.equal(record("T16f", context.stage_gate.parity_capture_authorized === false, "S4 unreleased: parity capture is not authorized"), true);
    assert.equal(record("T16h", materialization.parity_status === "NOT_STARTED", "S4 unreleased: parity status is NOT_STARTED"), true);
  } else {
    assert.equal(record("T16e", context.stage_gate.s4_release === "RELEASED_CANDIDATE_ONLY", "S4 candidate present: release is RELEASED_CANDIDATE_ONLY"), true);
    assert.equal(record("T16f", context.stage_gate.parity_capture_authorized === true, "S4 candidate present: parity capture is authorized"), true);
    assert.equal(record("T16h", materialization.parity_status === "CANDIDATE_PENDING_CENTRAL", "S4 candidate present: parity status is CANDIDATE_PENDING_CENTRAL"), true);
    // The two canonical files must agree, or one of them is stale.
    assert.equal(record("T16h2", context.stage_gate.s4_release === materialization.stage_gate.s4_release
      && context.stage_gate.parity_capture_authorized === materialization.stage_gate.parity_capture_authorized,
    "authority-context and materialization stage_gate agree on the S4 release"), true);
    assert.equal(record("T16h3", materialization.stage_gate.parity_status === materialization.parity_status,
      "materialization stage_gate.parity_status matches materialization.parity_status"), true);
  }

  assert.equal(record("T16g", context.stage_gate.parity_ref === null && materialization.parity_ref === null, "no parity reference exists"), true);
  assert.equal(record("T16i", !fs.existsSync(acceptedParity), "no accepted-parity.json exists; S4 candidate is never promoted"), true);
  assert.equal(record("T16j", s4Exists
    ? context.stage_gate.parity_status === "CANDIDATE_PENDING_CENTRAL"
    : true,
  "an S4 candidate directory implies CANDIDATE_PENDING_CENTRAL, never a stale HOLD"), true);
  assert.equal(record("T16k", manifest.capture_surface.mode === "STANDALONE_AUTHORITY_SURFACE", "manifest capture surface mode"), true);
  assert.equal(record("T16l", baseline.status === "ACCEPTED" && baseline.source_id === "CDX005", "S2 accepted baseline promoted with matching identity"), true);
  assert.equal(record("T16m", baseline.screenshot_equality_claimed === false && baseline.baseline_stable === false, "baseline records no screenshot equality claim"), true);
  assert.equal(record("T16n", baseline.report.commit === "960fd4ad407d5b996f644064c6ed1a5b7383d7ab", "baseline references the immutable S2 workdiary report commit"), true);
  assert.equal(record("T16o", baseline.capture.states_total === 36 && baseline.capture.total_png === 72, "baseline carries the accepted 36-state / 72-capture figures"), true);
});

test("T17 duplicate-variant governance, no Product adoption, no Lineage58 adoption", () => {
  assert.equal(record("T17a", manifest.duplicate_variant_status === "SINGLE_EXECUTABLE_NO_DUPLICATE", "capsule status is SINGLE_EXECUTABLE_NO_DUPLICATE"), true);
  assert.notEqual(manifest.duplicate_variant_status, "DUPLICATE_COPY_SAME_SHA");
  const note = manifest.duplicate_variant_note;
  assert.equal(record("T17b", typeof note.finding === "string" && note.finding.length > 0, "duplicate_variant_note records the finding"), true);
  assert.equal(record("T17c", note.finding.includes("SUPERSEDED") && note.finding.includes("NOT_AUTHORITY"), "note records V1 as superseded / not authority"), true);
  assert.equal(record("T17d", note.finding.includes("DUPLICATE_COPY_SAME_SHA"), "note records the same-SHA duplicate copy classification"), true);
  const fu = note.follow_up_adjudication;
  assert.equal(record("T17e", ["at_utc", "by", "basis", "finding"].every((f) => typeof fu[f] === "string" && fu[f].trim().length > 0), "structurally valid follow_up_adjudication block"), true);
  assert.equal(record("T17f", note.adjudicated_by.includes("5887518417"), "adjudication cites the CENTRAL S3 release comment"), true);
  assert.equal(record("T17g", manifest.product_adoption === false && context.product_adoption === false, "no Product adoption"), true);
  assert.equal(record("T17h", manifest.lineage58_adoption === false && context.lineage58_adoption === false, "no Lineage58 adoption"), true);
  assert.equal(record("T17i", manifest.drive_mutation === 0, "zero Drive mutation recorded"), true);
  assert.equal(record("T17j", manifest.repo_mutation_outside_capsule === 1, "exactly one repository mutation outside this capsule"), true);
  assert.deepEqual(manifest.repo_mutation_outside_capsule_files, ["tests/duplicate-variant-governance-contract.test.mjs"], "the single outside-capsule file is the corpus-wide Codex count test");
  assert.equal(record("T17j2", manifest.repo_mutation_outside_capsule_files.length === manifest.repo_mutation_outside_capsule, "the declared count matches the declared file list length"), true);
  assert.equal(record("T17j3", manifest.repo_mutation_outside_capsule_files[0].startsWith("tests/") && manifest.repo_mutation_outside_capsule_files[0].endsWith(".test.mjs"), "the outside-capsule file is a test file, not Source or Codex runtime"), true);
  assert.equal(record("T17j4", fs.existsSync(path.join(REPO_ROOT, manifest.repo_mutation_outside_capsule_files[0])), "the named outside-capsule file actually exists in the repository"), true);
  assert.equal(record("T17k", manifest.master_rows.length === 1 && manifest.master_rows[0] === "MST105", "identity stays in the MST->CDX namespace, no renumbering"), true);
  const forbidden = fs.readdirSync(path.join(CAPSULE), { withFileTypes: true })
    .map((e) => e.name)
    .filter((n) => !["manifest.json", "authority-context.json", "baseline", "original", "split", "evidence", "tests"].includes(n));
  assert.equal(record("T17l", forbidden.length === 0, "capsule contains only the canonical S3 entries"), true);
});

test("T18 evidence record is coherent, S4 fail-closed, and the run summary is written to OS temp only", () => {
  const evidence = readJson("evidence/s3/roundtrip.json");
  assert.equal(record("T18a", evidence.source_id === "CDX005" && evidence.codex_id === "CDX005", "evidence identity is CDX005"), true);
  assert.equal(record("T18b", evidence.authority.bytes === AUTHORITY_BYTES && evidence.authority.sha256 === AUTHORITY_SHA256, "evidence authority lock"), true);
  assert.equal(record("T18c", evidence.round_trip_byte_identity === true && evidence.round_trip_bytes === AUTHORITY_BYTES, "evidence asserts byte-identical round-trip"), true);
  assert.equal(record("T18d", evidence.local_asset_preservation.hash_match === "80/80" && evidence.local_asset_preservation.original_equals_split === true, "evidence records 80/80 with identical vendored copies"), true);
  assert.equal(record("T18e", evidence.local_asset_preservation.reencoded === false && evidence.local_asset_preservation.url_rewritten === false && evidence.local_asset_preservation.resized === false, "evidence records no re-encode, no URL rewrite, no resize"), true);
  assert.equal(record("T18f", evidence.derived_required_count === undefined || evidence.local_asset_preservation.derived_required_count === 80, "derived required count is 80"), true);
  assert.equal(record("T18g", evidence.s4_started === false && evidence.s4_executed_by === null, "S4 not started and no executor recorded"), true);
  assert.equal(record("T18h", evidence.parity_acceptance_claimed === false && evidence.parity_status === "NOT_STARTED" && evidence.parity_ref === null, "no parity claim"), true);
  assert.equal(record("T18i", evidence.stage_gate.s4_release === "HOLD_CENTRAL" && evidence.stage_gate.parity_capture_authorized === false && evidence.stage_gate.source_split_parity_pass === false && evidence.stage_gate.parity_ref === null, "evidence stage gate is fail-closed"), true);
  assert.equal(record("T18j", evidence.source_mutation === 0 && evidence.product_adoption === 0 && evidence.lineage58_adoption === 0, "no source mutation, no Product adoption, no Lineage58 adoption"), true);
  assert.equal(record("T18k", evidence.drive_authority_readback.drive_mutation === 0, "Drive readback recorded as read-only"), true);
  assert.equal(record("T18l", evidence.motion_inventory.prefers_reduced_motion_occurrences === 0 && evidence.motion_inventory.math_random_occurrences === 3, "frozen D1/D2/D3 motion and randomness inventory preserved"), true);
  assert.equal(record("T18m", JSON.stringify(evidence.motion_inventory.keyframes) === JSON.stringify(["drift", "spin", "scan", "burst"]), "all four authored keyframes preserved"), true);
  assert.equal(record("T18n", evidence.base_main === "814f121b00a553753c667dfd8eb3c4c8fbe284c5", "evidence pins the fresh origin/main it was generated from"), true);
  assert.equal(record("T18o", evidence.branch === "feat/589-cdx005-s3-mechanical-capsule", "evidence pins the S3 branch"), true);
  assert.equal(record("T18p", evidence.drive_authority_readback.drive_object_count === 80, "80 Drive asset objects were read back read-only"), true);
  assert.equal(record("T18q", evidence.output_exists_in_capsule === undefined, "no run-scoped fields leak into the committed record"), true);
});

test("ZZ99 S3 run evidence is written to an OS temp directory, never into the capsule", () => {
  const passed = checks.filter((c) => c.pass).length;
  const failed = checks.filter((c) => !c.pass).length;
  const out = {
    schema_version: "1.0",
    codex_id: "CDX005",
    source_id: "CDX005",
    stage: "S3_MECHANICAL_SPLIT",
    authority: { bytes: AUTHORITY_BYTES, sha256: AUTHORITY_SHA256 },
    round_trip_byte_identical: true,
    round_trip_bytes: AUTHORITY_BYTES,
    round_trip_sha256: AUTHORITY_SHA256,
    boundaries: { style_open: styleOpen, style_close: styleClose, script_open: scriptOpen, script_close: scriptClose },
    glue: { css_link: CSS_LINK, script_src: SCRIPT_SRC },
    outputs: {
      "split/index.html": { bytes: indexBytes.length, sha256: sha256(indexBytes), git_blob_sha1: gitBlobSha1(indexBytes) },
      "split/styles.css": { bytes: Buffer.byteLength(css, "utf8"), sha256: sha256(read("split/styles.css")), git_blob_sha1: gitBlobSha1(read("split/styles.css")) },
      "split/script.js": { bytes: Buffer.byteLength(js, "utf8"), sha256: sha256(read("split/script.js")), git_blob_sha1: gitBlobSha1(read("split/script.js")) },
    },
    asset_count: originalAssets.length,
    asset_hash_match: "80/80",
    checks,
    passed,
    failed,
    result: failed === 0 ? "PASS" : "FAIL",
    s4_started: false,
    parity_capture_authorized: false,
    parity_acceptance_claimed: false,
    parity_ref: null,
    parity_status: "NOT_STARTED",
    source_mutation: 0,
    product_adoption: 0,
    lineage58_adoption: 0,
  };
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cdx005-s3-roundtrip-"));
  const file = path.join(dir, "roundtrip-run.json");
  fs.writeFileSync(file, `${JSON.stringify(out, null, 2)}\n`, "utf8");
  console.log(`CDX005_S3_ROUNDTRIP_RESULT=${out.result} passed=${passed} failed=${failed}`);
  console.log(`CDX005_S3_ROUNDTRIP_RUN_EVIDENCE=${file}`);
  console.log(`CDX005_S3_ROUNDTRIP_COMMITTED_RECORD_UNTOUCHED=src/04_codex/CDX005/evidence/s3/roundtrip.json`);
  assert.equal(failed, 0, `all S3 checks must pass, got ${failed} failure(s)`);
});
