
const angles=['000','045','090','135','180','225','270','315'];
const path=(id,a)=>`assets/turnarounds/transparent/${id}_${a}.png`;
const looks=[
 {id:'A',gender:'male',name:'Crystal Night',title:'CRYSTAL<br>NIGHT',kind:'STAGE',kicker:'검은 무대 위, 은빛으로 남은 순간',desc:'크리스털 자수 수트와 무대의 긴장을 동일 인물 8방향 피규어로 잠급니다.',look:'BLACK CRYSTAL SUIT',time:'VIDEO 01 · 00:14.8 — 00:17.2',accent:'#ff5c8f',rgb:'255,92,143',identity:98,outfit:98,bg:'radial-gradient(circle at 62% 55%,#48142d 0%,#171020 28%,#06070b 65%,#020307 100%)'},
 {id:'B',gender:'male',name:'Cobalt Rush',title:'COBALT<br>RUSH',kind:'PERFORMANCE',kicker:'푸른 재킷과 함께 빨라진 심장',desc:'코발트 모토 재킷의 지퍼와 실루엣을 모든 각도에서 이어지는 하나의 룩으로 만듭니다.',look:'COBALT MOTO',time:'VIDEO 12 · 01:02.1 — 01:04.4',accent:'#4ba7ff',rgb:'75,167,255',identity:97,outfit:99,bg:'radial-gradient(circle at 64% 53%,#123f73 0%,#0b172b 32%,#05070c 67%,#020308 100%)'},
 {id:'C',gender:'male',name:'Ivory Pause',title:'IVORY<br>PAUSE',kind:'AIRPORT',kicker:'잠시 멈춘 시간의 아이보리 온도',desc:'공항 영상 속 니트와 자연스러운 자세를 조용한 프리미엄 피규어로 보관합니다.',look:'IVORY AIRPORT',time:'VIDEO 21 · 02:11.0 — 02:14.6',accent:'#f2d9ae',rgb:'242,217,174',identity:98,outfit:96,bg:'radial-gradient(circle at 64% 48%,#67523e 0%,#231d1c 30%,#09090b 66%,#030305 100%)'},
 {id:'D',gender:'male',name:'Rose Velvet',title:'ROSE<br>VELVET',kind:'STAGE',kicker:'로즈 벨벳으로 선명해진 실루엣',desc:'크롭 재킷의 길이와 검은 라펠까지 후면에서도 끊기지 않도록 고정했습니다.',look:'ROSE VELVET SUIT',time:'VIDEO 37 · 03:44.2 — 03:46.0',accent:'#e88aaa',rgb:'232,138,170',identity:96,outfit:99,bg:'radial-gradient(circle at 63% 52%,#5c203c 0%,#21111f 32%,#08070b 66%,#030206 100%)'},
 {id:'E',gender:'male',name:'Silver Replay',title:'SILVER<br>REPLAY',kind:'REHEARSAL',kicker:'연습실에서 발견한 가장 편한 모습',desc:'실버 데님과 움직임의 여유를 영상 속 리허설 순간 그대로 회전 컬렉션에 넣었습니다.',look:'SILVER DENIM',time:'VIDEO 44 · 04:19.7 — 04:22.5',accent:'#a8c5d8',rgb:'168,197,216',identity:97,outfit:97,bg:'radial-gradient(circle at 64% 51%,#29414d 0%,#141d23 31%,#07090d 66%,#020307 100%)'},
 {id:'F',gender:'female',name:'Black Spark',title:'BLACK<br>SPARK',kind:'STAGE',kicker:'검은 드레스 위로 번진 은빛 불꽃',desc:'드레스의 크리스털 장식과 부츠를 유지한 채 여성 피규어도 완전한 8방향으로 확장했습니다.',look:'BLACK SILVER DRESS',time:'VIDEO 53 · 05:08.0 — 05:10.8',accent:'#ff7eb2',rgb:'255,126,178',identity:98,outfit:99,bg:'radial-gradient(circle at 64% 52%,#5e193b 0%,#241020 32%,#08070c 67%,#020307 100%)'},
 {id:'G',gender:'female',name:'Ivory Bloom',title:'IVORY<br>BLOOM',kind:'VLOG',kicker:'햇살처럼 조용히 피어난 기억',desc:'아이보리 니트와 플리츠의 움직임을 부드러운 360도 룩으로 보존했습니다.',look:'IVORY KNIT',time:'VIDEO 62 · 06:22.4 — 06:25.1',accent:'#ffd7b7',rgb:'255,215,183',identity:99,outfit:97,bg:'radial-gradient(circle at 64% 50%,#74503f 0%,#2b1d1c 31%,#0c090c 66%,#030306 100%)'},
 {id:'H',gender:'female',name:'Cobalt Beat',title:'COBALT<br>BEAT',kind:'PERFORMANCE',kicker:'코발트 블루가 리듬을 기억하는 방식',desc:'재킷의 블루와 체인 장식을 앞뒤 모든 각도에서 하나의 퍼포먼스 룩으로 연결합니다.',look:'COBALT STAGE',time:'VIDEO 71 · 07:17.3 — 07:19.9',accent:'#4a8cff',rgb:'74,140,255',identity:97,outfit:99,bg:'radial-gradient(circle at 63% 50%,#163d78 0%,#101932 31%,#06070d 67%,#020307 100%)'},
 {id:'I',gender:'female',name:'Rose Tempo',title:'ROSE<br>TEMPO',kind:'STAGE',kicker:'핑크 조명과 검은 리듬의 교차',desc:'로즈 재킷과 팬츠의 옆선을 8개 시점으로 이어 영상의 템포를 입체로 재현했습니다.',look:'ROSE BLACK SUIT',time:'VIDEO 89 · 08:09.1 — 08:11.6',accent:'#f06d9f',rgb:'240,109,159',identity:98,outfit:99,bg:'radial-gradient(circle at 63% 51%,#68213f 0%,#251020 32%,#09070c 67%,#020306 100%)'},
 {id:'J',gender:'female',name:'Denim Echo',title:'DENIM<br>ECHO',kind:'REHEARSAL',kicker:'꾸미지 않은 순간이 오래 남을 때',desc:'데님 재킷의 자연스러운 드레이프와 짧은 단발을 회전 중에도 동일하게 유지했습니다.',look:'DENIM REHEARSAL',time:'VIDEO 100 · 09:33.6 — 09:36.1',accent:'#78bde3',rgb:'120,189,227',identity:99,outfit:98,bg:'radial-gradient(circle at 64% 51%,#214b64 0%,#11212d 31%,#06090d 67%,#020307 100%)'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let current=0,angle=0,auto=true,autoTimer,autoToken=0,dragging=false,startX=0,lastWheel=0;const saved=new Set();
function imgs(l){return angles.map(a=>path(l.id,a))}
function build(){angles.forEach((a,i)=>{const b=document.createElement('b');if(i===0)b.className='on';$('#angleDots').appendChild(b)});looks.forEach((l,i)=>{const c=document.createElement('button');c.className='card';c.dataset.i=i;c.dataset.gender=l.gender;c.style.setProperty('--card-accent',l.accent);c.style.setProperty('--card-rgb',l.rgb);c.innerHTML=`<img src="${path(l.id,'000')}" alt="${l.name}"><span class="card-copy"><b class="card-no">${String(i+1).padStart(2,'0')} · ${l.gender.toUpperCase()}</b><strong class="card-name">${l.name}</strong><small class="card-look">${l.look}</small></span>`;c.onclick=()=>select(i,true);$('#grid').appendChild(c)});select(0,false);autoLoop(850)}
function select(i,user=false){current=(i+looks.length)%looks.length;angle=0;const l=looks[current],w=$('#heroWrap');w.classList.add('out');setTimeout(()=>{document.documentElement.style.setProperty('--accent',l.accent);document.documentElement.style.setProperty('--accent-rgb',l.rgb);$('#scene').style.background=l.bg;$('#hero').src=path(l.id,'000');w.classList.remove('out')},190);$('#num').textContent=String(current+1).padStart(2,'0');$('#kind').textContent=`${l.kind} · ${l.gender.toUpperCase()}`;$('#title').innerHTML=l.title;$('#kicker').textContent=l.kicker;$('#desc').textContent=l.desc;$('#identity').textContent=l.identity;$('#outfit').textContent=l.outfit;$('#source').textContent=l.time;$('#save').textContent=saved.has(current)?'♥ LOOK SAVED':'♡ SAVE LOOK';$$('.card').forEach((c,n)=>c.classList.toggle('active',n===current));updateAngle();if(user)restartAuto(900)}
function updateAngle(){const l=looks[current];$('#hero').src=path(l.id,angles[angle]);$('#angleText').textContent=angles[angle]+'°';$$('#angleDots b').forEach((b,i)=>b.classList.toggle('on',i===angle))}
function autoLoop(delay=370,token=autoToken){clearTimeout(autoTimer);if(!auto)return;autoTimer=setTimeout(()=>{if(!auto||token!==autoToken)return;angle=(angle+1)%8;updateAngle();if(angle===0){autoTimer=setTimeout(()=>{if(!auto||token!==autoToken)return;select(current+1,false);autoLoop(900,token)},950)}else autoLoop(340,token)},delay)}
function restartAuto(delay=700){clearTimeout(autoTimer);autoToken++;if(auto)autoLoop(delay,autoToken)}
$('#autoBtn').onclick=()=>{auto=!auto;$('#autoBtn').innerHTML=auto?'Ⅱ&nbsp;&nbsp; AUTO 360°':'▶&nbsp;&nbsp; PLAY 360°';restartAuto()};$('#next').onclick=()=>select(current+1,true);
$('#figureZone').onpointerdown=e=>{dragging=true;startX=e.clientX;e.currentTarget.setPointerCapture(e.pointerId);clearTimeout(autoTimer);autoToken++};$('#figureZone').onpointermove=e=>{if(!dragging)return;const d=e.clientX-startX;if(Math.abs(d)>24){angle=(angle+(d>0?-1:1)+8)%8;startX=e.clientX;updateAngle()}};$('#figureZone').onpointerup=()=>{dragging=false;restartAuto(700)};
window.addEventListener('wheel',e=>{if(e.target.closest('.panel'))return;if(Date.now()-lastWheel<620)return;lastWheel=Date.now();select(current+(e.deltaY>0?1:-1),true)},{passive:true});window.addEventListener('keydown',e=>{if(e.key==='ArrowRight')select(current+1,true);if(e.key==='ArrowLeft')select(current-1,true)});
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.toggle('active',x===b));const f=b.dataset.filter;$$('.card').forEach((c,i)=>c.classList.toggle('hide',f!=='all'&&(f==='saved'?!saved.has(i):c.dataset.gender!==f)))});
$('#save').onclick=()=>{saved.add(current);$('#save').textContent='♥ LOOK SAVED';const burst=$('#burst');burst.innerHTML='';for(let n=0;n<25;n++){const p=document.createElement('i'),a=Math.PI*2*n/25,r=70+Math.random()*150;p.className='particle';p.style.setProperty('--x',Math.cos(a)*r+'px');p.style.setProperty('--y',Math.sin(a)*r+'px');p.style.animationDelay=Math.random()*.12+'s';burst.appendChild(p)}const t=$('#toast');t.textContent=`LOOK ${String(current+1).padStart(2,'0')} · ${looks[current].name.toUpperCase()} SAVED`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)};
const modal=$('#modal');function openModal(){clearTimeout(autoTimer);autoToken++;modal.classList.add('open')}function closeModal(){modal.classList.remove('open');restartAuto()}$('#openTop').onclick=openModal;$('#openUpload').onclick=openModal;$('#close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
$('#video').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#fileName').textContent=f.name.toUpperCase();$('#process').classList.add('show');let p=0;const run=setInterval(()=>{p=Math.min(100,p+7+Math.floor(Math.random()*11));$('#bar').style.width=p+'%';$('#percent').textContent=p+'%';$$('.step').forEach((s,i)=>s.classList.toggle('done',p>i*23+8));if(p===100){clearInterval(run);setTimeout(()=>{closeModal();const t=$('#toast');t.textContent='100 MOMENTS FOUND · CHOOSE YOUR 10 LOOKS';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)},550)}},240)};$('#sound').onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==='♬'?'♩':'♬';
build();
