export const SOURCE_TRACK_26_FILM_STUDIO = {
  issue: 490,
  parentIssue: 344,
  masterRow: 82,
  productJob: 'TOOLS',
  sourceFamily: '26_메모리필름스튜디오',
  sourceFile: '01_메모리필름스튜디오_v1.html',
  sourcePath: 'reference/source-tracks-snapshot/26_메모리필름스튜디오/01_메모리필름스튜디오_v1.html',
  sourceBytes: 48201,
  sourceBlob: '04a729148fdd4f29d4192aab6211e89dea8614b2',
  sourceSha256: '52bf3308053b1c805b963e775f41085caa7cdfdf123df0a7009a401a80e293d6',
  route: '/design-lab/source-tracks/26/v1/donor',
  disposition: 'USE_AS_VISUAL_FUNCTION_DONOR',
  editorBase: 'useTreeMoments(treeId) + canonical Tree/Moment/media authority',
  durableWriteAdded: false,
  donorElements: [
    'storyboard scene rail and reorder',
    'film stage preview',
    'scene duration and aspect composition',
    'camera framing presets',
    'timeline scrub and transport',
    'selected-scene inspector',
  ],
  sourceOnlyState: [
    'hard-coded tree-felix / season-03 / m1 fixture data',
    'local project object',
    'localStorage project save/load',
    'client-only poster PNG export',
    'client-only MediaRecorder WebM export',
  ],
  forbiddenPromotion: [
    'parallel editor backend',
    'new persistence or database schema',
    'new media storage',
    'fake save or fake durable edit state',
  ],
} as const;
