
  (function(){
    'use strict';
    var app=document.getElementById('app'),menuBtn=document.getElementById('menuBtn'),menuPanel=document.getElementById('menuPanel'),menuScrim=document.getElementById('menuScrim'),menuText=document.getElementById('menuText'),menuCloseBtn=document.getElementById('menuCloseBtn');
    var mediaWindow=document.getElementById('mediaWindow'),layers=[].slice.call(document.querySelectorAll('.media-layer')),dots=[].slice.call(document.querySelectorAll('.chapter-dot'));
    var chapterNo=document.getElementById('chapterNo'),chapterTitle=document.getElementById('chapterTitle'),chapterCopy=document.getElementById('chapterCopy'),mediaName=document.getElementById('mediaName'),mediaIndex=document.getElementById('mediaIndex'),chapterStatus=document.getElementById('chapterStatus'),chapterProgress=document.getElementById('chapterProgress');
    var cursor=document.getElementById('cursor'),loader=document.getElementById('loader'),loaderCount=document.getElementById('loaderCount'),pageTransition=document.getElementById('pageTransition'),transitionLabel=document.getElementById('transitionLabel'),transitionCount=document.getElementById('transitionCount');
    var portalView=document.getElementById('portalView'),portalFrame=document.getElementById('portalFrame'),portalTitle=document.getElementById('portalTitle'),portalNewWindow=document.getElementById('portalNewWindow'),portalCloseBtn=document.getElementById('portalCloseBtn');
    var indexView=document.getElementById('indexView'),indexCloseBtn=document.getElementById('indexCloseBtn'),enterLabel=document.getElementById('enterLabel');
    var waterCanvas=document.getElementById('waterCanvas'),waterContext=waterCanvas.getContext('2d'),waterMarks=[],waterDpr=1,lastSheenAt=0,lastRippleAt=0,lastSoundAt=0,lastPointerX=innerWidth*.66,lastPointerY=innerHeight*.48;
    var SOUND_KEY='lovetree-global-sound-v2',current=0,menuOpen=false,indexOpen=false,portalOpen=false,wheelLock=false,soundOn=readSoundPreference(),audioContext=null,audioMaster=null,surfaceNoise=null,loaderSoundStage=-1,mouseX=innerWidth*.66,mouseY=innerHeight*.48;
    var chapters=[
      {name:'Biosphere',status:'BIOSPHERE / ONLINE',title:'Memory becomes<br>a living world.',copy:'A quiet entrance to every person, place and promise you want to keep alive.'},
      {name:'People',status:'PEOPLE / CONNECTED',title:'Every person<br>holds a universe.',copy:'Portraits become living portals, connecting emotion, time and the stories between us.'},
      {name:'Bloom',status:'BLOOM / GROWING',title:'What we keep<br>continues to bloom.',copy:'Flowers and luminous fruit appear as shared memories gather around the LoveTree.'},
      {name:'Trace',status:'TRACE / DISCOVERED',title:'A small trace<br>can open everything.',copy:'A voice, a message or one image becomes the beginning of another memory world.'}
    ];
    var chapterDestinations=[
      {label:'Biosphere',path:'../../15_러브트리_메모리바이오스피어_인터랙티브대문_V1/버전2/최종본.html'},
      {label:'Human Trace',path:'../../../[01_러브트리]/03_디자인채택본/68_인물감정경로_모션아카이브/V6_CODEX_PORTALS/68_V3.3_COMPARE_LAUNCHER.html'},
      {label:'Liquid Bloom',path:'../../13_러브트리_리퀴드글라스_인피니트비디오월_V1/최종본.html'},
      {label:'Memory Orbit',path:'../../14_러브트리_로테이팅메모리인덱스_V1/최종본.html'}
    ];
    function pad(n){return String(n).padStart(3,'0');}
    function readSoundPreference(){try{return localStorage.getItem(SOUND_KEY)==='on';}catch(error){return false;}}
    function saveSoundPreference(){try{localStorage.setItem(SOUND_KEY,soundOn?'on':'off');}catch(error){}}
    function updateSoundUI(){var button=document.getElementById('soundBtn');button.classList.toggle('sound-on',soundOn);document.getElementById('soundText').textContent=soundOn?'Sound on':'Sound off';button.setAttribute('aria-pressed',String(soundOn));}
    function playDoubleTap(first,second){playTone(first,.052,'sine',.042);setTimeout(function(){playTone(second,.044,'sine',.032);},48);}
    function openMenu(){if(menuOpen)return;menuOpen=true;app.classList.add('menu-open');menuPanel.setAttribute('aria-hidden','false');menuBtn.setAttribute('aria-expanded','true');menuText.textContent='Close';playDoubleTap(485,680);}
    function closeMenu(){if(!menuOpen)return;menuOpen=false;app.classList.remove('menu-open');menuPanel.setAttribute('aria-hidden','true');menuBtn.setAttribute('aria-expanded','false');menuText.textContent='Menu';playDoubleTap(420,310);}
    function toggleMenu(){if(menuOpen)closeMenu();else openMenu();}
    function setChapter(index){current=(index+chapters.length)%chapters.length;var c=chapters[current],destination=chapterDestinations[current];layers.forEach(function(layer,i){layer.classList.toggle('active',i===current);});dots.forEach(function(dot,i){dot.classList.toggle('active',i===current);});chapterNo.textContent='CHAPTER '+String(current+1).padStart(2,'0')+' / 04';chapterTitle.innerHTML=c.title;chapterCopy.textContent=c.copy;mediaName.textContent=c.name;mediaIndex.textContent=String(current+1).padStart(2,'0')+' — 04';chapterStatus.textContent=c.status;chapterProgress.style.width=((current+1)/chapters.length*100)+'%';enterLabel.textContent='Enter '+destination.label;document.getElementById('talkBtn').setAttribute('aria-label','Enter '+destination.label);playTone(270+current*44,.052,'triangle',.03);}
    function initAudio(){if(audioContext)return;var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioContext=new AC();audioMaster=audioContext.createGain();audioMaster.gain.value=.9;audioMaster.connect(audioContext.destination);var length=Math.round(audioContext.sampleRate*.055);surfaceNoise=audioContext.createBuffer(1,length,audioContext.sampleRate);var data=surfaceNoise.getChannelData(0);for(var i=0;i<length;i++){var envelope=Math.pow(1-i/length,2.6);data[i]=(Math.random()*2-1)*envelope;}}
    function resumeAudio(){if(!soundOn)return;initAudio();if(!audioContext)return;if(audioContext.state==='suspended')audioContext.resume().catch(function(){});}
    function setSound(value){soundOn=!!value;saveSoundPreference();updateSoundUI();if(soundOn){resumeAudio();setTimeout(function(){playDoubleTap(520,720);},20);}else if(audioContext&&audioContext.state==='running')audioContext.suspend().catch(function(){});}
    function playTone(freq,duration,type,volume){if(!soundOn)return;initAudio();if(!audioContext||audioContext.state==='suspended')return;var o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime;o.type=type||'sine';o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(volume||.035,now+.006);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(audioMaster);o.start(now);o.stop(now+duration+.025);}
    function playSoftSweep(duration){if(!soundOn)return;resumeAudio();if(!audioContext||audioContext.state==='suspended')return;var o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime,durationValue=duration||.34;o.type='sine';o.frequency.setValueAtTime(170,now);o.frequency.exponentialRampToValueAtTime(330,now+durationValue);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.022,now+.045);g.gain.exponentialRampToValueAtTime(.0001,now+durationValue);o.connect(g).connect(audioMaster);o.start(now);o.stop(now+durationValue+.02);}
    function playSurface(speed,x){if(!soundOn||!audioContext||audioContext.state==='suspended')return;var nowMs=performance.now();if(nowMs-lastSoundAt<72||speed<3)return;lastSoundAt=nowMs;var now=audioContext.currentTime,panner=audioContext.createStereoPanner?audioContext.createStereoPanner():null,drop=audioContext.createOscillator(),dropGain=audioContext.createGain(),source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),noiseGain=audioContext.createGain(),output=audioContext.createGain();drop.type='sine';drop.frequency.setValueAtTime(430+Math.min(330,speed*4.2),now);drop.frequency.exponentialRampToValueAtTime(280+Math.min(160,speed*1.8),now+.055);dropGain.gain.setValueAtTime(.0001,now);dropGain.gain.exponentialRampToValueAtTime(.018,now+.004);dropGain.gain.exponentialRampToValueAtTime(.0001,now+.064);source.buffer=surfaceNoise;filter.type='bandpass';filter.frequency.value=1250+Math.min(1500,speed*13);filter.Q.value=.72;noiseGain.gain.setValueAtTime(.012,now);noiseGain.gain.exponentialRampToValueAtTime(.0001,now+.05);output.gain.value=Math.min(1,0.72+speed*.008);drop.connect(dropGain).connect(output);source.connect(filter).connect(noiseGain).connect(output);if(panner){panner.pan.value=Math.max(-.72,Math.min(.72,(x/innerWidth-.5)*1.45));output.connect(panner).connect(audioMaster);}else output.connect(audioMaster);drop.start(now);drop.stop(now+.08);source.start(now);}
    function hideTransition(){pageTransition.classList.add('leaving');setTimeout(function(){pageTransition.classList.remove('open','leaving');pageTransition.setAttribute('aria-hidden','true');},470);}
    function transitionTo(path,label,event){var x=event&&event.clientX||innerWidth*.82,y=event&&event.clientY||innerHeight*.16,target=new URL(path,location.href).href;pageTransition.style.setProperty('--tx',x+'px');pageTransition.style.setProperty('--ty',y+'px');transitionLabel.textContent=label||'Opening portal';transitionCount.textContent='000';pageTransition.classList.remove('leaving');pageTransition.classList.add('open');pageTransition.setAttribute('aria-hidden','false');closeMenu();closeIndex();playSoftSweep(.48);playTone(540,.12,'sine',.024);addSheen(x,y,24,0,true);var start=performance.now();function tick(now){var p=Math.min(1,(now-start)/900);transitionCount.textContent=pad(Math.round(p*100));if(p<1)requestAnimationFrame(tick);else{portalTitle.textContent=(label||'LoveTree portal')+' / connected view';portalNewWindow.href=target;portalFrame.src=target;portalOpen=true;portalView.classList.add('active');portalView.setAttribute('aria-hidden','false');setTimeout(hideTransition,780);}}requestAnimationFrame(tick);}
    function closePortal(){if(!portalOpen)return;portalOpen=false;portalView.classList.remove('active');portalView.setAttribute('aria-hidden','true');playSoftSweep(.24);playTone(310,.055,'sine',.014);setTimeout(function(){if(!portalOpen)portalFrame.src='about:blank';},520);}
    function openIndex(){if(indexOpen)return;closeMenu();indexOpen=true;indexView.classList.add('active');indexView.setAttribute('aria-hidden','false');playSoftSweep(.34);}
    function closeIndex(){if(!indexOpen)return;indexOpen=false;indexView.classList.remove('active');indexView.setAttribute('aria-hidden','true');playTone(300,.04,'sine',.012);}
    function resizeWater(){waterDpr=Math.min(2,window.devicePixelRatio||1);waterCanvas.width=Math.round(innerWidth*waterDpr);waterCanvas.height=Math.round(innerHeight*waterDpr);waterCanvas.style.width=innerWidth+'px';waterCanvas.style.height=innerHeight+'px';waterContext.setTransform(waterDpr,0,0,waterDpr,0,0);}
    function addFlow(x0,y0,x1,y1,speed,burst){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;var angle=Math.atan2(y1-y0,x1-x0),normal=angle+Math.PI/2,curve=(Math.sin(performance.now()*.012)+Math.cos((x1+y1)*.015))*Math.min(18,4+speed*.22);waterMarks.push({kind:'flow',x0:x0,y0:y0,x1:x1,y1:y1,cx:(x0+x1)*.5+Math.cos(normal)*curve,cy:(y0+y1)*.5+Math.sin(normal)*curve,life:1,width:burst?92:Math.min(68,20+speed*.72),hue:(performance.now()*.055+waterMarks.length*39)%360});if(burst)waterMarks.push({kind:'ripple',x:x1,y:y1,life:1,size:22,hue:(performance.now()*.06)%360});if(waterMarks.length>90)waterMarks.splice(0,waterMarks.length-90);}
    function addSheen(x,y,speed,angle,burst){var length=burst?110:Math.max(14,Math.min(90,speed*1.8)),x0=x-Math.cos(angle||0)*length,y0=y-Math.sin(angle||0)*length;addFlow(x0,y0,x,y,speed,burst);}
    function drawWater(){waterContext.clearRect(0,0,innerWidth,innerHeight);waterContext.lineCap='round';waterContext.lineJoin='round';for(var i=waterMarks.length-1;i>=0;i--){var mark=waterMarks[i];mark.life-=mark.kind==='ripple'?.018:.016;if(mark.life<=0){waterMarks.splice(i,1);continue;}if(mark.kind==='ripple'){waterContext.save();waterContext.globalCompositeOperation='source-over';waterContext.translate(mark.x,mark.y);waterContext.scale(1.65,.72);waterContext.strokeStyle='hsla('+mark.hue+',82%,58%,'+(.09*mark.life)+')';waterContext.lineWidth=2;waterContext.shadowColor='hsla('+((mark.hue+85)%360)+',90%,68%,'+(.22*mark.life)+')';waterContext.shadowBlur=20;waterContext.beginPath();waterContext.arc(0,0,mark.size,0,Math.PI*2);waterContext.stroke();waterContext.restore();mark.size+=1.7;continue;}var dx=mark.x1-mark.x0,dy=mark.y1-mark.y0,length=Math.max(1,Math.hypot(dx,dy)),nx=-dy/length,ny=dx/length;for(var band=0;band<4;band++){var offset=(band-1.5)*6.5,hue=(mark.hue+band*76)%360,alpha=(band===1||band===2?.07:.05)*mark.life;waterContext.save();waterContext.globalCompositeOperation='source-over';waterContext.strokeStyle='hsla('+hue+',82%,67%,'+alpha+')';waterContext.lineWidth=mark.width*(band===1||band===2?.82:.58)*(0.55+mark.life*.45);waterContext.shadowColor='hsla('+hue+',88%,68%,'+(.24*mark.life)+')';waterContext.shadowBlur=24;waterContext.beginPath();waterContext.moveTo(mark.x0+nx*offset,mark.y0+ny*offset);waterContext.quadraticCurveTo(mark.cx+nx*offset,mark.cy+ny*offset,mark.x1+nx*offset,mark.y1+ny*offset);waterContext.stroke();waterContext.restore();}waterContext.save();waterContext.globalCompositeOperation='soft-light';waterContext.strokeStyle='rgba(255,255,255,'+(.34*mark.life)+')';waterContext.lineWidth=Math.max(3,mark.width*.18);waterContext.beginPath();waterContext.moveTo(mark.x0,mark.y0);waterContext.quadraticCurveTo(mark.cx,mark.cy,mark.x1,mark.y1);waterContext.stroke();waterContext.restore();}requestAnimationFrame(drawWater);}
    menuBtn.addEventListener('click',toggleMenu);menuCloseBtn.addEventListener('click',closeMenu);menuScrim.addEventListener('click',closeMenu);portalCloseBtn.addEventListener('click',closePortal);indexCloseBtn.addEventListener('click',closeIndex);document.getElementById('homeBtn').addEventListener('click',function(){if(portalOpen)closePortal();if(indexOpen)closeIndex();setChapter(0);closeMenu();});
    document.getElementById('backBtn').addEventListener('click',function(){if(portalOpen){closePortal();return;}if(indexOpen){closeIndex();return;}if(history.length>1)history.back();else setChapter(0);});
    document.getElementById('talkBtn').addEventListener('click',function(e){var destination=chapterDestinations[current];transitionTo(destination.path,'Enter '+destination.label,e);});
    document.getElementById('soundBtn').addEventListener('click',function(){setSound(!soundOn);});
    dots.forEach(function(dot){dot.addEventListener('click',function(){setChapter(Number(dot.dataset.chapter));});});
    document.querySelectorAll('.menu-link').forEach(function(link){link.addEventListener('mouseenter',function(){playTone(390,.038,'sine',.028);});link.addEventListener('click',function(e){var action=link.dataset.action;if(action==='home'){closeMenu();setChapter(0);return;}if(action==='chapters'){openIndex();return;}if(link.dataset.path)transitionTo(link.dataset.path,link.querySelector('.menu-link-label').textContent,e);});});
    document.querySelectorAll('.index-card').forEach(function(card){card.addEventListener('mouseenter',function(){playTone(520+Number(card.dataset.index)*55,.038,'sine',.024);});card.addEventListener('click',function(e){var index=Number(card.dataset.index),destination=chapterDestinations[index];setChapter(index);transitionTo(destination.path,'Enter '+destination.label,e);});});
    addEventListener('wheel',function(e){if(menuOpen||indexOpen||portalOpen||wheelLock||Math.abs(e.deltaY)<8)return;wheelLock=true;setChapter(current+(e.deltaY>0?1:-1));setTimeout(function(){wheelLock=false;},650);},{passive:true});
    addEventListener('keydown',function(e){if(e.key==='Escape'){if(portalOpen){closePortal();return;}if(indexOpen){closeIndex();return;}if(menuOpen){closeMenu();return;}}if(!menuOpen&&!indexOpen&&!portalOpen&&e.key==='ArrowRight')setChapter(current+1);if(!menuOpen&&!indexOpen&&!portalOpen&&e.key==='ArrowLeft')setChapter(current-1);if(!indexOpen&&!portalOpen&&e.key.toLowerCase()==='m')toggleMenu();});
    addEventListener('pointerdown',function(){if(soundOn)resumeAudio();},{passive:true});
    addEventListener('pointermove',function(e){mouseX=e.clientX;mouseY=e.clientY;cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';var hot=!!e.target.closest('button,a');cursor.classList.toggle('hot',hot);app.style.setProperty('--mx',(e.clientX/innerWidth*100).toFixed(2)+'%');app.style.setProperty('--my',(e.clientY/innerHeight*100).toFixed(2)+'%');var nx=e.clientX/innerWidth-.5,ny=e.clientY/innerHeight-.5;mediaWindow.style.setProperty('--tilt-x',(nx*2.4).toFixed(2)+'deg');mediaWindow.style.setProperty('--tilt-y',(ny*-1.8).toFixed(2)+'deg');app.style.setProperty('--oa-x',(nx*-13).toFixed(1)+'px');app.style.setProperty('--oa-y',(ny*-10).toFixed(1)+'px');app.style.setProperty('--ob-x',(nx*10).toFixed(1)+'px');app.style.setProperty('--ob-y',(ny*8).toFixed(1)+'px');var dx=e.clientX-lastPointerX,dy=e.clientY-lastPointerY,distance=Math.hypot(dx,dy),now=performance.now();if(now-lastSheenAt>24&&distance>2){lastSheenAt=now;addFlow(lastPointerX,lastPointerY,e.clientX,e.clientY,distance,false);if(now-lastRippleAt>130&&distance>7){lastRippleAt=now;waterMarks.push({kind:'ripple',x:e.clientX,y:e.clientY,life:.72,size:9,hue:(now*.06)%360});}}playSurface(distance,e.clientX);lastPointerX=e.clientX;lastPointerY=e.clientY;});
    addEventListener('pointerleave',function(){cursor.style.opacity='0';});addEventListener('pointerenter',function(){cursor.style.opacity='1';});
    var loadStart=performance.now(),assets=[].slice.call(document.images),settled=false;Promise.all(assets.map(function(img){return img.complete?Promise.resolve():new Promise(function(resolve){img.addEventListener('load',resolve,{once:true});img.addEventListener('error',resolve,{once:true});});})).then(function(){settled=true;});
    function playLoaderCue(value){var stages=[18,50,78,99],frequencies=[190,270,380,540];while(loaderSoundStage+1<stages.length&&value>=stages[loaderSoundStage+1]){loaderSoundStage++;playTone(frequencies[loaderSoundStage],.055+loaderSoundStage*.018,loaderSoundStage===3?'sine':'triangle',.009+loaderSoundStage*.003);if(loaderSoundStage===3)playSoftSweep(.32);}}
    function loadTick(now){var elapsed=now-loadStart,sim=Math.min(94,elapsed/12),value=settled?Math.min(100,94+(elapsed-650)/8):sim;value=Math.max(0,value);loaderCount.textContent=pad(Math.round(value));playLoaderCue(value);if(value<100||elapsed<950)requestAnimationFrame(loadTick);else setTimeout(function(){loader.classList.add('done');addSheen(innerWidth*.58,innerHeight*.48,20,0,true);},170);}
    addEventListener('resize',resizeWater);addEventListener('pageshow',function(){soundOn=readSoundPreference();updateSoundUI();if(soundOn)resumeAudio();});document.addEventListener('visibilitychange',function(){if(!document.hidden&&soundOn)resumeAudio();});
    updateSoundUI();resizeWater();drawWater();if(soundOn)resumeAudio();
    var previewParams=new URLSearchParams(location.search),previewMode=previewParams.get('preview'),previewChapter=Math.max(0,Math.min(3,Number(previewParams.get('chapter'))||0));if(previewMode){loader.classList.add('done');loader.style.display='none';if(previewMode==='menu')setTimeout(openMenu,80);if(previewMode==='index'){indexView.style.transition='none';indexView.style.opacity='1';indexView.style.visibility='visible';indexView.style.transform='none';setTimeout(openIndex,80);}if(previewMode==='water'){setTimeout(function(){var previous={x:innerWidth*.08,y:innerHeight*.78};for(var step=1;step<=16;step++){var point={x:innerWidth*(.08+step*.038),y:innerHeight*(.78-step*.021+Math.sin(step*.72)*.034)};addFlow(previous.x,previous.y,point.x,point.y,30+step*1.7,false);previous=point;}waterMarks.push({kind:'ripple',x:previous.x,y:previous.y,life:.88,size:12,hue:210});},80);}if(previewMode==='portal')setTimeout(function(){var destination=chapterDestinations[previewChapter];transitionTo(destination.path,'Enter '+destination.label,{clientX:innerWidth*.82,clientY:innerHeight*.16});},80);if(previewMode==='portalopen'){setTimeout(function(){var destination=chapterDestinations[previewChapter],target=new URL(destination.path,location.href).href;portalTitle.textContent='Enter '+destination.label+' / connected view';portalNewWindow.href=target;portalFrame.src=target;portalOpen=true;portalView.classList.add('active');portalView.setAttribute('aria-hidden','false');},80);}}else requestAnimationFrame(loadTick);
    setChapter(previewChapter);
  })();
  