(()=>{
'use strict';
const stage=document.getElementById('stage'); const ring=document.getElementById('railRing'); const station=document.getElementById('station');
const nodes=[...document.querySelectorAll('.rail-node')]; const scenes=[...document.querySelectorAll('.scene')]; const terrains=[...document.querySelectorAll('.terrain-layer')];
const count=document.getElementById('count'); const pf=document.getElementById('progressFill'); const pl=document.getElementById('progressLabel'); const live=document.getElementById('liveStatus');
const max=scenes.length-1; const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let phase=0,targetPhase=0,velocity=0,dragging=false,pointerId=null,lastX=0,lastT=0,snapTimer=0,lastActive=-1; let lastFrame=performance.now();
let metrics={w:innerWidth,h:innerHeight,R:900,cx:innerWidth/2,cy:-700,stationY:150,nodeStep:.22,sceneSpacing:1200};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const momentMeta=[{"id": "m01", "label": "FIRST GLIMPSE", "title": "처음 눈이 멈춘 순간", "note": "아직 이유는 몰랐지만 한 번 더 보고 싶었다.", "why": "그 표정이 계속 생각나서 다음 장면까지 찾아봤다."}, {"id": "m02", "label": "STILLNESS", "title": "그 장면 앞에서 조금 더 머물렀다.", "note": "멈춰 있는 장면인데 이상하게 시간이 길게 느껴졌다.", "why": "조용히 앉아 있던 순간이 궁금증을 더 오래 붙잡았다."}, {"id": "m03", "label": "PORTRAIT", "title": "무대보다 사람이 궁금해지기 시작했다.", "note": "한 장의 초상이 다음 영상의 이유가 되었다.", "why": "무대가 아닌 표정과 자세를 더 보고 싶어졌다."}, {"id": "m04", "label": "LOOK BACK", "title": "지나쳤는데 다시 보고 싶어졌다.", "note": "한 번 지나간 장면이 뒤늦게 마음에 남았다.", "why": "돌아보는 실루엣이 다음 기억을 다시 불러냈다."}, {"id": "m05", "label": "BETWEEN SCENES", "title": "다음 장면을 찾기 전 잠깐 멈춘 기억.", "note": "사이의 정적도 경로의 일부가 되었다.", "why": "기대어 있던 짧은 쉼이 다음 장면을 기다리게 했다."}, {"id": "m06", "label": "VOICE", "title": "이 목소리 때문에 다음 영상을 찾았다.", "note": "형태가 소리의 기억으로 이어졌다.", "why": "마이크를 든 순간이 실제 목소리를 다시 듣게 만들었다."}, {"id": "m07", "label": "LOVETREE", "title": "기억은 이어지고, 경로는 나의 Tree가 된다.", "note": "여섯 Moment와 다섯 Connection이 하나의 경로가 되었다.", "why": "처음의 감정이 다음 탐색을 만들고, 그 연결이 나의 Tree가 된다."}];
const momentById=Object.fromEntries(momentMeta.map((m,i)=>[m.id,{...m,index:i,src:scenes[i].querySelector('.sculpture').src}]));
function measure(){const w=innerWidth,h=innerHeight,mobile=w<=700; const stationY=mobile?112:Math.min(158,Math.max(126,h*.145)); const R=mobile?Math.max(286,w*.76):Math.max(690,w*.48); metrics={w,h,R,cx:w/2,cy:stationY-R,stationY,nodeStep:mobile?.30:.225,sceneSpacing:mobile?w*.88:Math.min(w*.68,1180)}; ring.style.width=ring.style.height=(R*2)+'px'; ring.style.left=(metrics.cx-R)+'px'; ring.style.top=(metrics.cy-R)+'px'; station.style.left=metrics.cx+'px'; station.style.top=stationY+'px'; render();}
function scheduleSnap(ms=180){clearTimeout(snapTimer);snapTimer=setTimeout(()=>{targetPhase=clamp(Math.round(targetPhase),0,max)},reduced?70:ms)}
function setTarget(v,allowVelocity=true){const next=clamp(v,0,max); if(!allowVelocity)velocity=0; targetPhase=next;}
function render(){
 const {w,h,R,cx,cy,nodeStep,sceneSpacing}=metrics; const nearest=clamp(Math.round(phase),0,max);
 nodes.forEach((n,i)=>{const angle=Math.PI/2+(phase-i)*nodeStep; const x=cx+R*Math.cos(angle), y=cy+R*Math.sin(angle); const d=Math.abs(i-phase); const vis=clamp(1-d*.18,0,1); n.style.transform=`translate3d(${x}px,${y}px,0) translate(-50%,-50%)`; n.style.opacity=String(vis); n.style.pointerEvents=(x>-120&&x<w+120&&y>-20&&y<230)?'auto':'none'; n.classList.toggle('active',d<.24); n.tabIndex=(Math.round(phase)===i)?0:-1; });
 scenes.forEach((s,i)=>{const d=i-phase; const x=d*sceneSpacing; const ad=Math.abs(d); const scale=clamp(1-ad*.035,.925,1); const op=clamp(1-ad*.48,.12,1); s.style.transform=`translate3d(calc(-50% + ${x}px),-50%,0) scale(${scale})`; s.style.opacity=String(op); s.style.zIndex=String(10-Math.round(ad*2)); s.classList.toggle('active',ad<.24); s.style.pointerEvents=ad<1.12?'auto':'none'; });
 terrains.forEach(t=>{const speed=parseFloat(t.dataset.speed||'.15'); const x=-(phase*metrics.w*speed); t.style.transform=`translate3d(${x}px,0,0)`;});
 const progress=max?phase/max:0; pf.style.transform=`scaleX(${clamp(progress,0,1)})`; count.textContent=String(nearest+1).padStart(2,'0')+' / '+String(max+1).padStart(2,'0'); pl.textContent='SCENE '+String(nearest+1).padStart(2,'0');
 if(nearest!==lastActive){lastActive=nearest;live.textContent=scenes[nearest]?.querySelector('.eyebrow')?.textContent||'Scene';}
 stage.dataset.phase=phase.toFixed(4);
}
function tick(now){const dt=Math.min(2.5,(now-lastFrame)/16.667);lastFrame=now;if(!dragging){const delta=targetPhase-phase;if(reduced){velocity=0;phase+=delta*Math.min(1,.32*dt)}else{velocity+=delta*.075*dt;velocity*=Math.pow(.80,dt);velocity=clamp(velocity,-.16,.16);phase+=velocity*dt}phase=clamp(phase,0,max);if((phase<=0&&velocity<0)||(phase>=max&&velocity>0))velocity*=.2;}render();requestAnimationFrame(tick)}
function onWheel(e){if(stage.classList.contains('overlay-open'))return;e.preventDefault(); const sens=matchMedia('(max-width:700px)').matches?.0018:.0023; const raw=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX; const inc=clamp(raw*sens,-.42,.42); targetPhase=clamp(targetPhase+inc,0,max); velocity+=inc*.22; scheduleSnap(175)}
stage.addEventListener('wheel',onWheel,{passive:false});
let gestureTarget=null,gestureScene=-1,gestureStartX=0,gestureStartY=0,gestureMoved=false;
stage.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return; if(e.target.closest('.chrome-ui')||e.target.closest('.rail-node'))return; dragging=true;pointerId=e.pointerId;stage.setPointerCapture?.(pointerId);stage.classList.add('dragging');lastX=e.clientX;lastT=performance.now();velocity=0;clearTimeout(snapTimer);gestureTarget=e.target.closest('.sculpture');gestureScene=gestureTarget?Number(gestureTarget.closest('.scene')?.dataset.scene):-1;gestureStartX=e.clientX;gestureStartY=e.clientY;gestureMoved=false;});
stage.addEventListener('pointermove',e=>{if(!dragging||e.pointerId!==pointerId)return;const now=performance.now();const dx=e.clientX-lastX;const dt=Math.max(8,now-lastT);if(Math.hypot(e.clientX-gestureStartX,e.clientY-gestureStartY)>9)gestureMoved=true;const dp=-dx/metrics.sceneSpacing; targetPhase=clamp(targetPhase+dp,0,max);phase=targetPhase;velocity=clamp(dp*(16.667/dt),-.15,.15);lastX=e.clientX;lastT=now;render();});
function release(e){if(!dragging||e.pointerId!==pointerId)return;dragging=false;stage.classList.remove('dragging');const tapped=gestureTarget&&!gestureMoved;const tappedScene=gestureScene;targetPhase=clamp(targetPhase+velocity*1.8,0,max);try{stage.releasePointerCapture?.(pointerId)}catch(_){}pointerId=null;scheduleSnap(125); if(tapped){const active=clamp(Math.round(phase),0,max);if(tappedScene===active)openMoment(momentMeta[tappedScene].id);else{setTarget(tappedScene);scheduleSnap(150);}} gestureTarget=null;gestureScene=-1;} stage.addEventListener('pointerup',release);stage.addEventListener('pointercancel',release);
nodes.forEach((n,i)=>n.addEventListener('click',e=>{e.stopPropagation();setTarget(i);scheduleSnap(170)}));
addEventListener('keydown',e=>{if(stage.classList.contains('overlay-open')&&e.key==='Escape'){closeOverlay();return}if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();setTarget(Math.min(max,Math.round(targetPhase)+1));scheduleSnap(120)}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();setTarget(Math.max(0,Math.round(targetPhase)-1));scheduleSnap(120)}else if(e.key==='Home'){setTarget(0);scheduleSnap(80)}else if(e.key==='End'){setTarget(max);scheduleSnap(80)}});
addEventListener('resize',measure,{passive:true});

// V1.1 viewer + menu layer: state does not rewrite phase.
const backdrop=document.getElementById('overlayBackdrop'),viewer=document.getElementById('viewer'),panel=document.getElementById('panel'),panelInner=document.getElementById('panelInner');
const viewerPoster=document.getElementById('viewerPoster'),viewerKicker=document.getElementById('viewerKicker'),viewerTitle=document.getElementById('viewerTitle'),viewerWhy=document.getElementById('viewerWhy'),viewerStatus=document.getElementById('viewerStatus');
const playMoment=document.getElementById('playMoment'),saveMoment=document.getElementById('saveMoment'),viewerTree=document.getElementById('viewerTree');
let overlayType=null,currentViewerId=null,revealTimer=0;
function openShell(which){stage.classList.add('overlay-open');backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');overlayType=which; if(which==='viewer'){viewer.classList.add('open');viewer.setAttribute('aria-hidden','false')}else{panel.classList.add('open');panel.setAttribute('aria-hidden','false')}}
function closeOverlay(){clearTimeout(revealTimer);viewer.classList.remove('open','reveal-ready','playing');panel.classList.remove('open');backdrop.classList.remove('open');viewer.setAttribute('aria-hidden','true');panel.setAttribute('aria-hidden','true');backdrop.setAttribute('aria-hidden','true');stage.classList.remove('overlay-open');playMoment.textContent='PLAY MOMENT';overlayType=null;}
let volatileSaved=new Set(); function savedSet(){try{volatileSaved=new Set(JSON.parse(localStorage.getItem('track62-saved')||JSON.stringify([...volatileSaved])));return new Set(volatileSaved)}catch(_){return new Set(volatileSaved)}}
function syncSave(id){const s=savedSet();const on=s.has(id);saveMoment.classList.toggle('saved',on);saveMoment.textContent=on?'SAVED':'SAVE';}
function openMoment(id){const m=momentById[id];if(!m)return;currentViewerId=id;viewerPoster.src=m.src;viewerPoster.alt=m.label+' Moment preview';viewerKicker.textContent=id==='m07'?'YOUR MEMORY PATH':'MOMENT FILM · '+String(m.index+1).padStart(2,'0');viewerTitle.textContent=m.title;viewerWhy.textContent=m.why;viewerStatus.textContent=id==='m07'?'PATH SUMMARY':'MEMORY REVEAL';viewerTree.textContent=id==='m07'?'MY TREE 보기':'MY TREE 보기';playMoment.textContent=id==='m07'?'REPLAY PATH':'PLAY MOMENT';syncSave(id);openShell('viewer');viewer.classList.remove('reveal-ready','playing');revealTimer=setTimeout(()=>viewer.classList.add('reveal-ready'),340);}
function panelHeader(kicker,title,copy=''){return `<div class="panel-kicker">${kicker}</div><h2 class="panel-title">${title}</h2>${copy?`<p class="panel-copy">${copy}</p>`:''}`}
function indexRows(kind){return `<div class="index-list">${momentMeta.map((m,i)=>`<button type="button" class="index-row" data-travel="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><strong>${m.label}</strong><span>${kind==='journal'?m.note:m.title}</span></button>`).join('')}</div>`}
function openPanel(type){document.getElementById('mobileNavSheet').classList.remove('open'); let body='';if(type==='about')body=panelHeader('ABOUT · TRACK 62','Memory Sculpture','좋아했던 순간은 사라지지 않는다. 저장한 Moment와 그 사이의 WHY NEXT가 하나씩 조각되어 나만의 LoveTree가 된다.');else if(type==='sculptures')body=panelHeader('SCULPTURES · INDEX','Seven forms')+indexRows('sculptures');else if(type==='journal')body=panelHeader('JOURNAL · MOMENT NOTES','What stayed')+indexRows('journal');else if(type==='films'){body=panelHeader('MEMORY FILMS · 01—06','Open a memory','조각상은 흑백으로 남고, 기억을 열 때만 제한적으로 색이 살아난다.')+`<div class="film-grid">${momentMeta.slice(0,6).map((m,i)=>`<button type="button" class="film-card" data-film="${m.id}"><img class="film-thumb" src="${momentById[m.id].src}" alt=""><span class="film-meta"><strong>${String(i+1).padStart(2,'0')} · ${m.label}</strong><span>${m.title}</span></span></button>`).join('')}</div>`}else{body=panelHeader('MY TREE · CURRENT EXHIBITION PATH','Your Memory Path','현재 전시에서 이어진 7개의 Moment 경로 요약이다.')+`<div class="tree-path">${momentMeta.map((m,i)=>`<span class="tree-chip">${String(i+1).padStart(2,'0')} ${m.label}</span>${i<momentMeta.length-1?'<span class="tree-link"></span>':''}`).join('')}</div><div class="tree-stats"><div class="tree-stat"><b>6</b><span>Human Moments</span></div><div class="tree-stat"><b>5</b><span>Connections</span></div><div class="tree-stat"><b>01</b><span>First Moment</span></div><div class="tree-stat"><b>01</b><span>LoveTree</span></div></div><div class="viewer-actions" style="margin-top:30px"><button type="button" class="action-btn primary" data-travel="6">LOVETREE로 이동</button><button type="button" class="action-btn" data-close-panel>다시 전시 보기</button></div>`}panelInner.innerHTML=body;openShell('panel');}

document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openPanel(b.dataset.panel)}));
document.getElementById('mobileMenuButton').addEventListener('click',e=>{e.stopPropagation();const s=document.getElementById('mobileNavSheet');s.classList.toggle('open');s.setAttribute('aria-hidden',s.classList.contains('open')?'false':'true')});
document.getElementById('viewerClose').addEventListener('click',closeOverlay);document.getElementById('panelClose').addEventListener('click',closeOverlay);backdrop.addEventListener('click',closeOverlay);
document.querySelectorAll('[data-open-moment]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const idx=Number(b.closest('.scene')?.dataset.scene);if(Math.round(phase)!==idx){setTarget(idx);scheduleSnap(140);return}openMoment(b.dataset.openMoment)}));
panel.addEventListener('click',e=>{const film=e.target.closest('[data-film]');if(film){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');openMoment(film.dataset.film);return}const travel=e.target.closest('[data-travel]');if(travel){const i=Number(travel.dataset.travel);closeOverlay();setTarget(i);scheduleSnap(140);return}if(e.target.closest('[data-close-panel]'))closeOverlay();});
playMoment.addEventListener('click',()=>{viewer.classList.toggle('playing');playMoment.textContent=viewer.classList.contains('playing')?(currentViewerId==='m07'?'PAUSE PATH':'PAUSE MOMENT'):(currentViewerId==='m07'?'REPLAY PATH':'PLAY MOMENT')});
saveMoment.addEventListener('click',()=>{if(!currentViewerId)return;const s=savedSet();if(s.has(currentViewerId))s.delete(currentViewerId);else s.add(currentViewerId);volatileSaved=new Set(s);try{localStorage.setItem('track62-saved',JSON.stringify([...s]))}catch(_){}syncSave(currentViewerId)});
viewerTree.addEventListener('click',()=>{viewer.classList.remove('open');viewer.setAttribute('aria-hidden','true');openPanel('tree')});

window.__track62={getState:()=>({phase,targetPhase,velocity,active:clamp(Math.round(phase),0,max),overlay:overlayType,viewerId:currentViewerId,metrics:{...metrics},nodes:nodes.map((n,i)=>{const r=n.getBoundingClientRect();return{i,x:r.left+r.width/2,y:r.top+r.height/2,active:n.classList.contains('active')}}),scenes:scenes.map((s,i)=>{const r=s.getBoundingClientRect();return{i,centerX:r.left+r.width/2,opacity:+getComputedStyle(s).opacity,active:s.classList.contains('active')}}),terrain:terrains.map((t,i)=>getComputedStyle(t).transform)}),setPhase:(v,instant=false)=>{targetPhase=clamp(v,0,max);if(instant){phase=targetPhase;velocity=0;render()}},wheelBy:d=>{targetPhase=clamp(targetPhase+d,0,max);scheduleSnap(175)},snap:()=>{targetPhase=clamp(Math.round(targetPhase),0,max)},openMoment,openPanel,closeOverlay,measure};
measure();requestAnimationFrame(tick);
})();