
  (function(){
    'use strict';
    var TOTAL=89,SLOTS=7;
    function pad(n){return String(n).padStart(3,'0');}function mod(n,m){return((n%m)+m)%m;}
    var first=['First','Living','Shared','Quiet','Red','Infinite','Hidden','Tender','Parallel','Golden'];var second=['Memory','Journey','Signal','Portrait','Orbit','Chapter','Feeling','Archive','Promise'];var sibling='../12_러브트리_리빙미디어스피어_인터랙티브대문_V1/assets/';
    var films=Array.from({length:TOTAL},function(_,i){var no=i+1;return{index:i,no:no,title:first[i%first.length]+' '+second[Math.floor(i/first.length)%second.length],src:sibling+'videos-v3/v3-'+pad(no)+'.mp4',poster:sibling+'posters-v3/poster-'+pad(no)+'.jpg'};});
    var deck=document.getElementById('deck'),stage=document.getElementById('stage'),drawer=document.getElementById('drawer'),indexGrid=document.getElementById('indexGrid'),slots=[];var selected=0,rotation=-18,targetRotation=-18,velocity=.035,auto=true,dragging=false,moved=false,pointerId=null,startX=0,startY=0,lastX=0,downSlot=-1,lastTime=performance.now(),frame=0;
    for(var s=0;s<SLOTS;s++){var panel=document.createElement('button');panel.className='panel';panel.dataset.slot=s;panel.setAttribute('aria-label','영상 카드');var front=document.createElement('span');front.className='face front';var img=document.createElement('img');img.alt='';front.appendChild(img);var video=document.createElement('video');video.muted=true;video.loop=true;video.playsInline=true;video.preload='none';front.appendChild(video);var copy=document.createElement('span');copy.className='panel-copy';copy.innerHTML='<small></small><h2></h2>';front.appendChild(copy);var back=document.createElement('span');back.className='face back';back.innerHTML='<span class="back-index"></span><span class="back-quote">Every memory changes when we return to it.</span><span class="back-footer">LoveTree · Moving Archive</span>';panel.appendChild(front);panel.appendChild(back);deck.appendChild(panel);slots.push({el:panel,front:front,img:img,video:video,copy:copy,back:back,filmIndex:0,z:0});}
    films.forEach(function(f){var item=document.createElement('button');item.className='index-item';item.dataset.index=f.index;item.setAttribute('aria-label',f.title+' 선택');var img=document.createElement('img');img.src=f.poster;img.alt='';img.loading='lazy';item.appendChild(img);var label=document.createElement('span');label.textContent=pad(f.no)+' '+f.title;item.appendChild(label);item.addEventListener('click',function(){selectFilm(f.index);drawer.classList.remove('open');});indexGrid.appendChild(item);});
    function updateSlots(){slots.forEach(function(slot,s){var pos=s-Math.floor(SLOTS/2),index=mod(selected+pos,TOTAL),f=films[index];slot.filmIndex=index;slot.el.classList.toggle('type-card',s===SLOTS-1);slot.el.classList.toggle('text-card',s===0);slot.front.innerHTML='';if(s===SLOTS-1){var meta=document.createElement('span');meta.className='type-meta';meta.innerHTML='<span>LT-'+pad(f.no)+'</span><span>Memory Type</span>';var letter=document.createElement('span');letter.className='type-letter';letter.textContent='LOVE'[selected%4];slot.front.appendChild(meta);slot.front.appendChild(letter);}else if(s===0){var editorial=document.createElement('span');editorial.className='editorial';editorial.innerHTML='<small>LoveTree · '+pad(f.no)+'</small><h2>Every moment<br>becomes part<br>of us.</h2><p>'+f.title+'<br>A moving memory kept alive.</p>';slot.front.appendChild(editorial);}else{slot.img=document.createElement('img');slot.img.src=f.poster;slot.img.alt='';slot.video=document.createElement('video');slot.video.muted=true;slot.video.loop=true;slot.video.playsInline=true;slot.video.preload='none';slot.video.dataset.src=f.src;slot.video.style.opacity='0';slot.front.appendChild(slot.img);slot.front.appendChild(slot.video);var copy=document.createElement('span');copy.className='panel-copy';copy.innerHTML='<small>LT-'+pad(f.no)+' · Moving memory</small><h2>'+f.title+'</h2>';slot.front.appendChild(copy);}slot.back.querySelector('.back-index').textContent='Memory '+pad(f.no)+' / '+pad(TOTAL);slot.el.setAttribute('aria-label',f.title+' 영상 열기');});document.getElementById('currentNo').textContent=pad(selected+1);document.querySelectorAll('.index-item').forEach(function(b){b.classList.toggle('active',Number(b.dataset.index)===selected);});}
    function selectFilm(index){selected=mod(index,TOTAL);updateSlots();}
    function openViewer(index){var f=films[index],wrap=document.getElementById('viewerMedia');wrap.innerHTML='';var video=document.createElement('video');video.src=f.src;video.poster=f.poster;video.controls=true;video.autoplay=true;video.playsInline=true;wrap.appendChild(video);video.play().catch(function(){video.muted=true;video.play().catch(function(){});});document.getElementById('viewerTitle').textContent=f.title;document.getElementById('viewerMeta').textContent='LOVE TREE · MEMORY '+pad(f.no)+' / '+pad(TOTAL);document.getElementById('viewer').classList.add('open');document.getElementById('viewer').setAttribute('aria-hidden','false');}
    function closeViewer(){var viewer=document.getElementById('viewer'),video=viewer.querySelector('video');if(video)video.pause();viewer.classList.remove('open');viewer.setAttribute('aria-hidden','true');setTimeout(function(){document.getElementById('viewerMedia').innerHTML='';},300);}
    stage.addEventListener('pointerdown',function(e){if(e.button!==0)return;dragging=true;moved=false;pointerId=e.pointerId;startX=lastX=e.clientX;startY=e.clientY;var panel=e.target.closest('.panel');downSlot=panel?Number(panel.dataset.slot):-1;stage.classList.add('dragging');stage.setPointerCapture(pointerId);e.preventDefault();});stage.addEventListener('pointermove',function(e){if(!dragging||e.pointerId!==pointerId)return;var dx=e.clientX-lastX;lastX=e.clientX;if(Math.hypot(e.clientX-startX,e.clientY-startY)>5)moved=true;targetRotation+=dx*.34;velocity=dx*.018;e.preventDefault();});function endPointer(e){if(!dragging||e.pointerId!==pointerId)return;dragging=false;stage.classList.remove('dragging');try{stage.releasePointerCapture(pointerId);}catch(err){}if(!moved&&downSlot>=0)openViewer(slots[downSlot].filmIndex);pointerId=null;downSlot=-1;}stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('wheel',function(e){selectFilm(selected+(e.deltaY>0?1:-1));targetRotation+=e.deltaY>0?10:-10;e.preventDefault();},{passive:false});
    function managePlayback(){var nearest=slots.filter(function(slot){return slot.video&&slot.video.dataset&&slot.video.dataset.src;}).sort(function(a,b){return b.z-a.z;}).slice(0,2);slots.forEach(function(slot){if(!slot.video||!slot.video.dataset||!slot.video.dataset.src)return;if(nearest.indexOf(slot)<0){slot.video.pause();slot.video.style.opacity='0';if(slot.img)slot.img.style.opacity='1';return;}if(!slot.video.getAttribute('src'))slot.video.src=slot.video.dataset.src;slot.video.style.opacity='1';if(slot.img)slot.img.style.opacity='0';if(!document.hidden)slot.video.play().catch(function(){});});}
    function render(now){frame++;var dt=Math.min(40,now-lastTime);lastTime=now;if(!dragging){if(auto)targetRotation+=dt*.0065;targetRotation+=velocity;velocity*=.94;}rotation+=(targetRotation-rotation)*.075;var rad=rotation*Math.PI/180,cos=Math.cos(rad),sin=Math.sin(rad),spacing=innerWidth<760?34:52;slots.forEach(function(slot,s){var pos=s-Math.floor(SLOTS/2),x0=pos*spacing,z0=-Math.abs(pos)*18,x=x0*cos+z0*sin,z=-x0*sin+z0*cos,y=Math.abs(pos)*2,ry=rotation+pos*3,scale=1-Math.abs(pos)*.025;slot.z=z;slot.el.style.transform='translate3d('+x.toFixed(2)+'px,'+y.toFixed(2)+'px,'+z.toFixed(2)+'px) rotateY('+ry.toFixed(2)+'deg) scale('+scale.toFixed(3)+')';slot.el.style.zIndex=String(1000+Math.round(z));slot.el.style.opacity=String(Math.max(.4,1-Math.abs(pos)*.085));});if(frame%20===0)managePlayback();requestAnimationFrame(render);}updateSlots();requestAnimationFrame(render);
    document.getElementById('prev').addEventListener('click',function(){selectFilm(selected-1);});document.getElementById('next').addEventListener('click',function(){selectFilm(selected+1);});document.getElementById('pause').addEventListener('click',function(){auto=!auto;this.textContent=auto?'Ⅱ':'▶';});document.getElementById('indexTrigger').addEventListener('click',function(){drawer.classList.toggle('open');});document.getElementById('drawerClose').addEventListener('click',function(){drawer.classList.remove('open');});document.getElementById('viewerClose').addEventListener('click',closeViewer);document.addEventListener('visibilitychange',managePlayback);document.addEventListener('keydown',function(e){if(e.key==='Escape'){drawer.classList.remove('open');closeViewer();}if(e.key==='ArrowLeft')selectFilm(selected-1);if(e.key==='ArrowRight')selectFilm(selected+1);});
  })();
  