const imageUrls=(()=>{var v=(typeof window!=="undefined"&&window!==null)?window.mediaVariant:void 0;if(v!=="A"&&v!=="B"){throw new Error("SRC068 variant contract violation: mediaVariant must be \"A\" or \"B\" (explicit; no default; fail closed). Received: "+String(v));}document.title=v==="A"?"LoveTree Track68 V3.3A · Codex Portals":"LoveTree Track68 V3.3B · Codex Portals";return v==="A"?["../images/01.png", "../images/02.png", "../images/03.png", "../images/04.png", "../images/05.png", "../images/06.png", "../images/07.png", "../images/08.png", "../images/09.png"]:["../images/동양인01.png", "../images/동양인02.png", "../images/동양인03.png", "../images/동양인04.png", "../images/동양인05.png", "../images/동양인06.png", "../images/동양인07.png", "../images/동양인08.png", "../images/동양인09.png"];})();
/*__SRC068_COMMON_JS_FOLLOWS__*/

const titles=['FIRST SPARK', 'SAVED MOMENT', 'WHY IT STAYED', 'NEXT CONNECTION', 'MY PATH', 'LOOK BACK', 'MY TREE', 'AFTERGLOW', 'REPLAY'];
const worksCatalog = [{"code":"68","name":"MOTION ARCHIVE","sub":"Portrait Emotional Path · Current","path":"","current":true},{"code":"67","name":"MEMORY TAPE","sub":"Persistent Ribbon World","path":"../../67_메모리테이프_인터랙티브롤/track67_v2.4.2_works_compare_menu.html","current":false},{"code":"65","name":"FIRST CLUE · V18","sub":"H3 Extended Motion Editing","path":"../../65_입덕단서_시네마틱에디토리얼/V18_디자인팀장15기_H3_EXTENDED_MOTION_EDITING_후보_선택/★_현재후보_65_V2.2.5_H3_EXTENDED_MOTION_EDITING_CINEMATIC.html","current":false},{"code":"C14","name":"ROTATING MEMORY INDEX","sub":"Codex 14 · Rotating Memory Index","path":"../../../../코덱스/14_러브트리_로테이팅메모리인덱스_V1/v2/개발본.html","current":false},{"code":"C13","name":"LIQUID GLASS VIDEO WALL","sub":"Codex 13 · Infinite Video Wall","path":"../../../../코덱스/13_러브트리_리퀴드글라스_인피니트비디오월_V1/최종본.html","current":false},{"code":"C12","name":"LIVING MEDIA SPHERE","sub":"Codex 12 · Interactive Front Door","path":"../../../../코덱스/12_러브트리_리빙미디어스피어_인터랙티브대문_V1/최종본.html","current":false},{"code":"C11","name":"MOONLIGHT FLOWER JOURNEY","sub":"Codex 11 · Living Flower Video Moment","path":"../../../../코덱스/11_러브트리_달빛꽃_감정여정_V2/V10_생명꽃_영상모먼트_러브트리대문/최종본_V10_생명꽃_영상모먼트_러브트리대문.html","current":false},{"code":"C10","name":"IDOL VIDEO ORBIT","sub":"Codex 10 · Video Orbit Carousel","path":"../../../../코덱스/10_러브트리_최애아이돌_영상오빗캐러셀_V1/최종본.html","current":false},{"code":"C09","name":"PETAL CAR JOURNEY","sub":"Codex 09 · Retro Future Emotion Journey","path":"../../../../코덱스/09_러브트리_꽃잎자동차_감정여정_V4/최종본.html","current":false},{"code":"C08","name":"CRYSTAL MEMORY ATELIER","sub":"Codex 08 · Crystal Memory Atelier","path":"../../../../코덱스/08_러브트리_크리스털기억_아틀리에_V3/최종본.html","current":false}];
const portalTargets=worksCatalog.filter(item=>!item.current);
const grid=document.getElementById('grid');
function buildLayout(){grid.innerHTML='';const cols=innerWidth<640?2:innerWidth<1024?3:4;let idx=0,row=0;while(idx<imageUrls.length){const a=(row*2+(row%2))%cols;const b=row%3===0?(a+2)%cols:-1;for(let c=0;c<cols;c++){const cell=document.createElement('div');cell.className='cell';if((c===a||c===b)&&idx<imageUrls.length){const momentIndex=idx;const target=portalTargets[momentIndex];const card=document.createElement('div');card.className='card';card.tabIndex=0;card.setAttribute('role','link');card.setAttribute('aria-label',`${titles[momentIndex]} — Open ${target.code} ${target.name}`);card.style.transformOrigin=c<cols/2?'right bottom':'left bottom';card.innerHTML=`<img src="${imageUrls[momentIndex]}" alt="Moment ${momentIndex+1}"><div class="portal-mark">${target.code} ↗</div><div class="tag">${String(momentIndex+1).padStart(2,'0')} · ${titles[momentIndex]}</div>`;const open=()=>openWork(target);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}});cell.appendChild(card);idx++;}grid.appendChild(cell)}row++}}
buildLayout();addEventListener('resize',buildLayout);
const cursor=document.getElementById('cursor');addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});
const leftVideo=document.getElementById('leftVideo'),rightVideo=document.getElementById('rightVideo');let last='right',mouseX=innerWidth/2;
addEventListener('mousemove',e=>mouseX=e.clientX);
function scrub(){if(matchMedia('(pointer:fine)').matches){const w=innerWidth,dead=Math.max(30,w*.05),mid=w/2;if(mouseX<mid-dead){last='right';rightVideo.style.display='block';leftVideo.style.display='none';if(rightVideo.duration&&!rightVideo.seeking)rightVideo.currentTime=Math.min(rightVideo.duration,((mid-dead-mouseX)/(mid-dead))*rightVideo.duration)}else if(mouseX>mid+dead){last='left';leftVideo.style.display='block';rightVideo.style.display='none';if(leftVideo.duration&&!leftVideo.seeking)leftVideo.currentTime=Math.min(leftVideo.duration,((mouseX-(mid+dead))/(w-(mid+dead)))*leftVideo.duration)}else{if(last==='left'){leftVideo.style.display='block';rightVideo.style.display='none'}else{rightVideo.style.display='block';leftVideo.style.display='none'}const v=last==='left'?leftVideo:rightVideo;if(!v.seeking)v.currentTime=0}}requestAnimationFrame(scrub)}requestAnimationFrame(scrub);
if(!matchMedia('(pointer:fine)').matches){leftVideo.style.display='block';rightVideo.style.display='none';leftVideo.loop=false;rightVideo.loop=false;leftVideo.play().catch(()=>{});leftVideo.onended=()=>{leftVideo.style.display='none';rightVideo.style.display='block';rightVideo.currentTime=0;rightVideo.play().catch(()=>{})};rightVideo.onended=()=>{rightVideo.style.display='none';leftVideo.style.display='block';leftVideo.currentTime=0;leftVideo.play().catch(()=>{})}}
const panel=document.getElementById('panel'),galleryInner=document.getElementById('galleryInner'),white=document.getElementById('white'),view=document.getElementById('view'),finalCopy=document.getElementById('finalCopy'),info=document.getElementById('info'),symbol=document.getElementById('symbol'),videoWrap=document.getElementById('videoWrap');let lastSymbol=0;const symbols=['♥','✦','↗','∞','•'];
function frame(){const y=scrollY,vh=innerHeight;const wrapH=galleryInner.scrollHeight;const maxScroll=Math.max(1,wrapH-vh*.8);document.getElementById('scroll-spacer').style.height=(vh+maxScroll+vh*2)+'px';if(y<=vh){const p=y/vh;panel.style.transform=`translateY(${(1-p)*vh}px)`;galleryInner.style.transform='translateY(0px)'}else{panel.style.transform='translateY(0)';galleryInner.style.transform=`translateY(${-Math.min(maxScroll,y-vh)}px)`}videoWrap.style.visibility=y>vh?'hidden':'visible';document.querySelectorAll('.card').forEach(card=>{const r=card.getBoundingClientRect();let s=0;if(r.bottom>0&&r.top<vh){const enter=Math.min(1,(vh-r.top)/(vh*.58));const exit=Math.min(1,r.bottom/(vh*.38));s=Math.max(0,Math.min(enter,exit))}card.style.transform=`scale(${s})`});const oStart=vh+maxScroll;if(y>oStart){const p=Math.max(0,Math.min(1,(y-oStart)/(vh*.85)));white.style.opacity=p;view.style.transform=`scale(${p})`;view.style.pointerEvents=p>.62?'auto':'none';finalCopy.style.opacity=p;info.style.transform=`translateY(${-p*150}px)`;info.style.opacity=1-p*.55}else{white.style.opacity=0;view.style.transform='scale(0)';view.style.pointerEvents='none';finalCopy.style.opacity=0;info.style.transform='none';info.style.opacity=1}if(performance.now()-lastSymbol>120&&y>10){symbol.textContent=symbols[Math.floor((y/160)%symbols.length)];lastSymbol=performance.now()}requestAnimationFrame(frame)}requestAnimationFrame(frame);

const worksOverlay=document.getElementById('worksOverlay');
const worksList=document.getElementById('worksList');
const worksClose=document.getElementById('worksClose');
function resolveWork(path){try{return new URL(path,location.href).href}catch(_){return path}}
function openWork(item){if(!item||item.current)return;window.open(resolveWork(item.path),'_blank','noopener')}
function renderWorks(){worksList.innerHTML='';worksCatalog.forEach(item=>{const row=document.createElement('div');row.className='work-row'+(item.current?' current':'');row.tabIndex=item.current?-1:0;row.innerHTML=`<div class="work-num">${item.code}</div><div class="work-name">${item.name}</div><div class="work-sub">${item.sub}</div><div class="work-action">${item.current?'CURRENT':'OPEN ↗'}</div>`;if(!item.current){row.addEventListener('click',()=>openWork(item));row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openWork(item)}})}worksList.appendChild(row)})}
function openWorks(){worksOverlay.classList.add('open');worksOverlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';worksClose.focus()}
function closeWorks(){worksOverlay.classList.remove('open');worksOverlay.setAttribute('aria-hidden','true');document.body.style.overflow='';view.focus()}
renderWorks();
worksClose.addEventListener('click',closeWorks);
worksOverlay.addEventListener('click',e=>{if(e.target===worksOverlay)closeWorks()});
view.addEventListener('click',openWorks);
view.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openWorks()}});
addEventListener('keydown',e=>{if(e.key==='Escape'&&worksOverlay.classList.contains('open'))closeWorks()});

