
  (function(){
    'use strict';
    var app=document.getElementById('app'),field=document.getElementById('fragmentField'),veins=document.getElementById('veins'),seeds=document.getElementById('seeds'),count=document.getElementById('count'),phase=document.getElementById('phase'),stageNo=document.getElementById('stageNo'),eyebrow=document.getElementById('eyebrow'),intro=document.getElementById('intro'),cursor=document.getElementById('cursor');
    var fragments=[],seedNodes=[],progress=0,target=0,running=false,startedAt=0,duration=6800,lastStage=-1,soundOn=false,audioContext=null,audioMaster=null,raf=0,mouseX=innerWidth*.5,mouseY=innerHeight*.5;
    var fragmentAssets=['cyber-01.png','cyber-02.png','cyber-03.png','cyber-04.png','cyber-05.png','cyber-06.png','cyber-07.png','cyber-08.png'];
    var phases=[{at:0,label:'Locating memory signal'},{at:.24,label:'Collecting image fragments'},{at:.52,label:'Growing connective light'},{at:.78,label:'Preparing memory world'}];
    var clipShapes=['polygon(8% 0,100% 7%,91% 100%,0 88%)','polygon(0 11%,88% 0,100% 91%,13% 100%)','polygon(13% 0,100% 16%,86% 100%,0 91%)','polygon(0 4%,95% 0,100% 84%,8% 100%)','polygon(6% 0,100% 11%,93% 92%,0 100%)'];
    function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
    function ease(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;}
    function pad(n){return String(n).padStart(3,'0');}
    function initAudio(){if(audioContext)return;var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioContext=new AC();audioMaster=audioContext.createGain();audioMaster.gain.value=.82;audioMaster.connect(audioContext.destination);}
    function tone(freq,duration,volume,type,delay){if(!soundOn)return;initAudio();if(!audioContext||audioContext.state==='suspended')return;var now=audioContext.currentTime+(delay||0),osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=type||'sine';osc.frequency.setValueAtTime(freq,now);osc.frequency.exponentialRampToValueAtTime(freq*.76,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(volume||.03,now+.006);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain).connect(audioMaster);osc.start(now);osc.stop(now+duration+.02);}
    function cue(stage){if(stage===lastStage)return;lastStage=stage;if(stage===0)tone(230,.09,.032,'triangle');if(stage===1){tone(420,.06,.037,'sine');tone(610,.05,.028,'sine',.055);}if(stage===2){tone(360,.11,.032,'triangle');tone(720,.08,.024,'sine',.08);}if(stage===3){tone(520,.13,.04,'sine');tone(760,.1,.032,'sine',.09);tone(980,.08,.021,'sine',.17);}}
    function setSound(value){soundOn=!!value;var button=document.getElementById('soundBtn');button.classList.toggle('sound-on',soundOn);button.setAttribute('aria-pressed',String(soundOn));document.getElementById('soundText').textContent=soundOn?'Sound on':'Sound off';if(soundOn){initAudio();if(audioContext&&audioContext.state==='suspended')audioContext.resume();tone(520,.07,.035,'sine');}}
    function layout(){var portrait=innerHeight>innerWidth*1.18,cols=portrait?4:5,rows=4,finalW=portrait?Math.min(innerWidth*.63,660):Math.min(innerWidth*.42,660),finalH=portrait?Math.min(innerHeight*.65,980):Math.min(innerHeight*.76,820),left=portrait?innerWidth*.31:innerWidth*.51,top=portrait?innerHeight*.22:innerHeight*.12,cellW=finalW/cols,cellH=finalH/rows;fragments.forEach(function(fragment,i){var col=i%cols,row=Math.floor(i/cols),angle=i*2.399,ring=(Math.min(innerWidth,innerHeight)*(.26+(i%5)*.045)),sx=innerWidth*.5+Math.cos(angle)*ring+(i%2?innerWidth*.12:-innerWidth*.1),sy=innerHeight*.5+Math.sin(angle)*ring,fx=left+col*cellW,fy=top+row*cellH;fragment.data={sx:sx,sy:sy,fx:fx,fy:fy,sw:cellW*(.46+(i%4)*.12),sh:cellH*(.42+((i+2)%4)*.12),fw:cellW+1,fh:cellH+1,sr:-68+(i*37)%136,fr:(i%3-1)*2.2,col:col,row:row,cols:cols,rows:rows};fragment.style.backgroundSize='cover';fragment.style.backgroundPosition=(44+(i%3)*6)+'% '+(14+(i%5)*8)+'%';fragment.style.clipPath=clipShapes[i%clipShapes.length];});drawVeins();}
    function createFragments(){for(var i=0;i<20;i++){var fragment=document.createElement('div');fragment.className='fragment';fragment.dataset.index=i;fragment.style.backgroundImage='url("assets/'+fragmentAssets[i%fragmentAssets.length]+'")';field.appendChild(fragment);fragments.push(fragment);}for(var s=0;s<8;s++){var seed=document.createElement('i');seed.className='seed';seed.style.setProperty('--sx',(11+(s*13)%83)+'%');seed.style.setProperty('--sy',(18+(s*19)%70)+'%');seed.style.setProperty('--r',String(s*43));seeds.appendChild(seed);seedNodes.push(seed);}layout();}
    function drawVeins(){var markup='';for(var i=0;i<12;i++){var x1=70+(i*83)%880,y1=120+(i*137)%770,x2=80+((i+4)*121)%850,y2=130+((i+7)*91)%760,cx=(x1+x2)*.5+Math.sin(i*2.2)*90,cy=(y1+y2)*.5+Math.cos(i*1.7)*75;markup+='<path d="M '+x1+' '+y1+' Q '+cx+' '+cy+' '+x2+' '+y2+'"/>'; }veins.innerHTML=markup;}
    function render(){var p=ease(progress),assemble=ease(clamp((progress-.08)/.78,0,1)),dissolve=clamp((progress-.89)/.11,0,1),parallaxX=(mouseX/innerWidth-.5),parallaxY=(mouseY/innerHeight-.5);document.documentElement.style.setProperty('--progress',progress.toFixed(4));fragments.forEach(function(fragment,i){var d=fragment.data,delay=(i%7)*.014,local=ease(clamp((assemble-delay)/(1-delay),0,1)),x=d.sx+(d.fx-d.sx)*local+parallaxX*(1-local)*(18+(i%5)*6),y=d.sy+(d.fy-d.sy)*local+parallaxY*(1-local)*(14+(i%4)*7),w=d.sw+(d.fw-d.sw)*local,h=d.sh+(d.fh-d.sh)*local,rotate=d.sr+(d.fr-d.sr)*local,depth=(1-local)*(40+(i%4)*22);fragment.style.width=w+'px';fragment.style.height=h+'px';fragment.style.opacity=String(clamp(.18+local*1.1-dissolve*1.24,0,1));fragment.style.transform='translate3d('+x+'px,'+y+'px,'+depth+'px) rotate('+rotate+'deg) scale('+(0.72+local*.28)+')';fragment.style.filter='saturate('+(0.65+local*.45)+') blur('+((1-local)*1.4)+'px)';});var stage=progress<.24?0:progress<.52?1:progress<.78?2:3;document.querySelectorAll('.stage').forEach(function(node,i){node.classList.toggle('active',i===stage);});count.textContent=pad(Math.round(progress*100));stageNo.textContent='0'+(stage+1)+' / 04';phase.textContent=phases[stage].label;eyebrow.textContent='A memory is gathering / '+pad(Math.round(progress*100));app.classList.toggle('ready',progress>=.995);cue(stage);}
    function tick(now){if(running){progress=clamp((now-startedAt)/duration,0,1);target=progress;if(progress>=1)running=false;}else progress+=(target-progress)*.095;render();raf=requestAnimationFrame(tick);}
    function start(){progress=0;target=0;lastStage=-1;app.classList.remove('ready');startedAt=performance.now();running=true;intro.classList.add('hidden');if(soundOn){initAudio();if(audioContext&&audioContext.state==='suspended')audioContext.resume();}tone(210,.11,.035,'triangle');}
    function replay(){tone(330,.06,.034,'sine');start();}
    document.getElementById('startBtn').addEventListener('click',function(){setSound(true);start();});
    document.getElementById('soundBtn').addEventListener('click',function(){setSound(!soundOn);});
    document.getElementById('replayBtn').addEventListener('click',replay);
    document.getElementById('aboutBtn').addEventListener('click',function(){target=target<.5?1:0;running=false;tone(target?620:310,.07,.032,'sine');});
    document.getElementById('enterBtn').addEventListener('click',function(){tone(560,.12,.045,'sine');});
    document.getElementById('closeBtn').addEventListener('pointerdown',function(){tone(390,.06,.038,'triangle');});
    addEventListener('pointermove',function(e){mouseX=e.clientX;mouseY=e.clientY;cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';cursor.classList.toggle('hot',!!e.target.closest('button,a'));document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px');});
    addEventListener('pointerleave',function(){cursor.style.opacity='0';});addEventListener('pointerenter',function(){cursor.style.opacity='1';});
    addEventListener('wheel',function(e){if(!intro.classList.contains('hidden'))return;running=false;target=clamp(target+e.deltaY*.0007,0,1);tone(290+target*390,.03,.014,'sine');},{passive:true});
    addEventListener('keydown',function(e){if(e.key===' '){e.preventDefault();intro.classList.contains('hidden')?replay():document.getElementById('startBtn').click();}if(e.key==='ArrowRight'){running=false;target=clamp(target+.08,0,1);}if(e.key==='ArrowLeft'){running=false;target=clamp(target-.08,0,1);}if(e.key.toLowerCase()==='s')setSound(!soundOn);});
    addEventListener('resize',layout);
    createFragments();requestAnimationFrame(tick);
    var params=new URLSearchParams(location.search),preview=params.get('preview');if(preview){intro.classList.add('hidden');intro.style.display='none';progress=target=preview==='complete'?1:clamp(Number(preview)/100,0,1);running=false;render();}
  })();
  