
const chars=[
 {id:'M01',gender:'m',name:'NOAH',type:'CENTER · QUIET FIRE',accent:'#ef76ad',accent2:'#70d9ef'},
 {id:'M02',gender:'m',name:'YUL',type:'DREAMER · SOFT LIGHT',accent:'#87b7ff',accent2:'#c59aff'},
 {id:'F01',gender:'f',name:'ARIA',type:'STORY · SPRING GAZE',accent:'#ff95bb',accent2:'#ffd6a5'},
 {id:'F02',gender:'f',name:'SENA',type:'MUSE · MOONLIGHT',accent:'#ad8aff',accent2:'#77d9e7'}
];
const emos=[
 ['neutral','◌','NEUTRAL','I’m listening.'],['smile','⌣','SMILE','You found me.'],['laugh','✦','LAUGH','That made me happy.'],['wink','◐','WINK','Just between us.'],['shy','♡','SHY','Don’t look too closely.'],['surprise','!','SURPRISE','I didn’t expect that.'],['angry','⌁','ANGRY','I’m not over it yet.'],['sing','♪','SING','This part is for you.'],['talk','…','TALK','Let me tell you.'],['cry','◠','CRY','Some moments still hurt.'],['touched','❀','TOUCHED','I’ll remember this.'],['sleepy','☾','SLEEPY','Stay a little longer.']
];
let current=0,emotion='neutral',front='A',auto=true,autoTimer,talkTimer,singTimer,hoverTimer,hoverSmile=false;const wrap=document.getElementById('portraitWrap'),a=document.getElementById('portraitA'),b=document.getElementById('portraitB'),stage=document.getElementById('stage'),lubt=document.getElementById('lubt'),lubtImg=document.getElementById('lubtImg');
function src(id,emo){return `assets/characters/${id}/${id}-${emo}.webp`}
chars.forEach((c,i)=>{let btn=document.createElement('button');btn.dataset.gender=c.gender;btn.className=i===0?'active':'';btn.innerHTML=`<img src="${src(c.id,'neutral')}"><label>0${i+1} · ${c.name}</label>`;btn.onclick=()=>selectChar(i);document.getElementById('cast').appendChild(btn)});
emos.forEach((e,i)=>{let btn=document.createElement('button');btn.className='emo'+(i===0?' on':'');btn.dataset.emo=e[0];btn.innerHTML=`<b>${e[1]}</b>${e[0].toUpperCase()}`;btn.onclick=()=>setEmotion(e[0],true);document.getElementById('emotions').appendChild(btn)});
function selectChar(i){stopModes();current=i;let c=chars[i];document.documentElement.style.setProperty('--accent',c.accent);document.documentElement.style.setProperty('--accent2',c.accent2);document.getElementById('castNum').textContent='0'+(i+1);document.getElementById('castName').textContent=c.name;document.getElementById('castType').textContent=c.type;document.querySelectorAll('.cast button').forEach((x,n)=>x.classList.toggle('active',n===i));setEmotion('neutral');callLubt('guide',`${c.name}의 표정을 만나볼까?`)}
function setEmotion(name,user=false){if(user){stopModes();hoverSmile=false}emotion=name;let e=emos.find(x=>x[0]===name),next=front==='A'?b:a;next.src=src(chars[current].id,name);wrap.classList.toggle('swap',front==='A');front=front==='A'?'B':'A';document.querySelectorAll('.emo').forEach(x=>x.classList.toggle('on',x.dataset.emo===name));document.getElementById('emotionTitle').textContent=e[2];document.getElementById('emotionLine').textContent='“'+e[3]+'”';document.getElementById('log').textContent=`${e[2]} · intensity ${document.getElementById('intensity').value}/10 · gaze tracking`;if(name==='sing')notes();if(name==='touched'||name==='laugh')petals();if(user)resetAuto()}
function resetAuto(){clearInterval(autoTimer);if(auto)autoTimer=setInterval(()=>{let pool=['neutral','smile','wink','shy','touched','sleepy'];setEmotion(pool[Math.floor(Math.random()*pool.length)])},4800)}
document.querySelectorAll('.filter button').forEach(f=>f.onclick=()=>{document.querySelectorAll('.filter button').forEach(x=>x.classList.remove('on'));f.classList.add('on');document.querySelectorAll('.cast button').forEach(x=>x.style.display=f.dataset.filter==='all'||x.dataset.gender===f.dataset.filter?'block':'none')});
stage.addEventListener('pointermove',e=>{let r=stage.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width*100,y=(e.clientY-r.top-r.height/2)/r.height*100;document.documentElement.style.setProperty('--mx',x);document.documentElement.style.setProperty('--my',y)});stage.addEventListener('pointerleave',()=>{document.documentElement.style.setProperty('--mx',0);document.documentElement.style.setProperty('--my',0);clearTimeout(hoverTimer);if(hoverSmile&&emotion==='smile')setEmotion('neutral');hoverSmile=false});wrap.onmouseenter=()=>{clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>{if(!talkTimer&&!singTimer){hoverSmile=true;setEmotion('smile')}},280)};wrap.onclick=()=>setEmotion(emotion==='wink'?'laugh':'wink',true);
document.getElementById('intensity').oninput=e=>{document.documentElement.style.setProperty('--intensity',e.target.value);document.getElementById('intVal').textContent=String(e.target.value).padStart(2,'0')};document.getElementById('liveliness').oninput=e=>{document.documentElement.style.setProperty('--life',e.target.value);document.getElementById('lifeVal').textContent=String(e.target.value).padStart(2,'0')};
document.getElementById('autoLife').onclick=e=>{auto=!auto;e.currentTarget.textContent='AUTO LIFE · '+(auto?'ON':'OFF');e.currentTarget.classList.toggle('on',auto);resetAuto()};
function stopModes(){clearInterval(talkTimer);clearInterval(singTimer);talkTimer=singTimer=null;document.getElementById('talkBtn').classList.remove('on');document.getElementById('singBtn').classList.remove('on')}
document.getElementById('talkBtn').onclick=e=>{if(talkTimer){stopModes();setEmotion('neutral');return}stopModes();e.currentTarget.classList.add('on');let flip=false;talkTimer=setInterval(()=>{setEmotion(flip?'talk':'smile');flip=!flip},520);showSpeech(document.getElementById('phrase').value)};
document.getElementById('singBtn').onclick=e=>{if(singTimer){stopModes();setEmotion('neutral');return}stopModes();e.currentTarget.classList.add('on');let seq=['sing','touched','sing','smile'],i=0;setEmotion('sing');singTimer=setInterval(()=>{setEmotion(seq[++i%seq.length])},760)};
document.getElementById('heartBtn').onclick=()=>{setEmotion('touched',true);petals();callLubt('heart','이 순간, 러브트리에 저장할게!')};document.getElementById('surpriseBtn').onclick=()=>setEmotion('surprise',true);document.getElementById('sayBtn').onclick=()=>{showSpeech(document.getElementById('phrase').value);setEmotion('talk',true)};document.getElementById('lubtBtn').onclick=()=>callLubt('scan','럽트가 감정을 스캔하고 있어!');document.getElementById('saveBtn').onclick=e=>{petals();e.currentTarget.textContent='✓ LIVING MOMENT SAVED';callLubt('bloom','새로운 기억 가지가 피어났어!')};
function showSpeech(t){let s=document.getElementById('speech');s.textContent=t||'오늘도 네 순간을 기억할게.';s.classList.add('show');setTimeout(()=>s.classList.remove('show'),3300)}
function notes(){let root=document.getElementById('notes');for(let i=0;i<8;i++){let n=document.createElement('i');n.className='note';n.textContent=i%2?'♪':'♫';n.style.left=(45+Math.random()*22)+'%';n.style.top=(50+Math.random()*18)+'%';n.style.setProperty('--dx',(Math.random()*140-70)+'px');root.appendChild(n);setTimeout(()=>n.remove(),1900)}}
function petals(){let root=document.getElementById('petals');for(let i=0;i<20;i++){let p=document.createElement('i');p.className='petal';p.textContent=i%4?'✦':'♥';p.style.left=(45+Math.random()*15)+'%';p.style.top=(45+Math.random()*12)+'%';p.style.setProperty('--dx',(Math.random()*500-250)+'px');p.style.setProperty('--dy',(Math.random()*360-80)+'px');root.appendChild(p);setTimeout(()=>p.remove(),2400)}}
const lubtPoses={idle:'lubt-idle.png',heart:'lubt-heart.png',scan:'lubt-scan.png',guide:'lubt-guide.png',magic:'lubt-magic.png',bloom:'lubt-bloom.png'};function callLubt(pose,msg){lubt.classList.add('talk','follow');lubt.style.left=(35+Math.random()*45)+'vw';lubt.style.top=(10+Math.random()*45)+'vh';lubtImg.src='assets/lubt/'+lubtPoses[pose];document.getElementById('lubtBubble').textContent=msg;setTimeout(()=>{lubt.classList.remove('talk','follow');lubtImg.src='assets/lubt/lubt-idle.png';lubt.style.left='300px';lubt.style.top='95px'},3600)}lubt.onclick=()=>callLubt('magic','어떤 표정을 만나고 싶어?');
a.src=src(chars[0].id,'neutral');b.src=src(chars[0].id,'smile');resetAuto();setTimeout(()=>callLubt('idle','안녕! 나는 러브트리요정, 럽트야.'),700);
