
const letters='ABCDEFGHIJ'.split(''),angles=[0,45,90,135,180,225,270,315];let current='A',angle=0,drag=false,lastX=0,auto=true,raf;
const figure=document.getElementById('figure'),cap=document.getElementById('capsule'),stage=document.getElementById('stage'),angleText=document.getElementById('angleText');
const names=['BLACK CRYSTAL','COBALT MOTO','IVORY AIRPORT','ROSE VELVET','SILVER DENIM','FEMALE 01','FEMALE 02','FEMALE 03','FEMALE 04','FEMALE 05'];
letters.forEach((l,i)=>{const b=document.createElement('button');b.className='figure-btn'+(i===0?' active':'');b.innerHTML=`<img src="assets/figures/${l}_000.png"><span>${l}</span>`;b.title=names[i];b.onclick=()=>{current=l;document.querySelectorAll('.figure-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');update()};document.getElementById('figures').appendChild(b)});
const colors=[['#ffc7e2','#ff81bc'],['#bdeeff','#4cc7ff'],['#dacbff','#9270ff'],['#ffe2a8','#ffad62'],['#d9fff2','#78d9b2']];colors.forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(i===0?' active':'');b.style.background=`linear-gradient(135deg,${c[0]},${c[1]})`;b.onclick=()=>{document.documentElement.style.setProperty('--glow',c[0]);document.documentElement.style.setProperty('--accent',c[1]);document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active')};document.getElementById('swatches').appendChild(b)});
function update(){let norm=((angle%360)+360)%360;let idx=Math.round(norm/45)%8;let a=angles[idx];figure.src=`assets/figures/${current}_${String(a).padStart(3,'0')}.png`;document.documentElement.style.setProperty('--my',`${(norm-180)*.12}deg`);document.documentElement.style.setProperty('--mx',`${Math.sin(norm*Math.PI/180)*5}deg`);angleText.textContent=`${a===0?'FRONT':a===180?'BACK':'ORBIT'} · ${String(a).padStart(3,'0')}°`}
function loop(){if(auto&&!drag){angle+=.18;update()}raf=requestAnimationFrame(loop)}loop();
stage.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;angle+=(e.clientX-lastX)*.65;lastX=e.clientX;update()});stage.addEventListener('pointerup',()=>drag=false);stage.addEventListener('wheel',e=>{e.preventDefault();angle+=e.deltaY*.09;update()},{passive:false});
document.getElementById('autoBtn').onclick=e=>{auto=!auto;e.currentTarget.textContent=auto?'Ⅱ':'▶'};document.querySelectorAll('.tag').forEach(t=>t.onclick=()=>{t.classList.toggle('on');document.querySelector('.'+t.dataset.target).classList.toggle('off')});
function burst(){const root=document.getElementById('burst');for(let i=0;i<34;i++){let p=document.createElement('span');p.className='petal';p.textContent=i%4?'✦':'♥';p.style.left=(48+Math.random()*8)+'%';p.style.top=(45+Math.random()*10)+'%';p.style.setProperty('--dx',(Math.random()*700-350)+'px');p.style.setProperty('--dy',(Math.random()*420-100)+'px');p.style.animationDelay=(Math.random()*.3)+'s';root.appendChild(p);setTimeout(()=>p.remove(),2800)}}
document.getElementById('saveBtn').onclick=e=>{burst();e.currentTarget.textContent='✓ CAPSULE SAVED'};document.getElementById('openBtn').onclick=()=>document.getElementById('drawer').classList.add('open');document.getElementById('closeDrawer').onclick=()=>document.getElementById('drawer').classList.remove('open');update();
