
const data=[
 {t:'SOURCE VIDEO',sub:'ORIGINAL',c:'#52d9ff',d:'모든 기억의 출발점. 업로드한 영상의 시간과 장면 정보가 보존됩니다.',m:'00:18.240 · Stage cam · 4K source<br>Identity locked · private archive',q:'“이 순간부터<br>나의 이야기가 시작됐다.”',chips:['VIDEO','ORIGIN','PRIVATE'],img:'A_000.png'},
 {t:'MOMENT CUT',sub:'TIMECODE',c:'#8d7cff',d:'마음을 움직인 정확한 2.4초를 원본 영상에서 고정합니다.',m:'IN 00:18.240 · OUT 00:20.640<br>Close-up · final chorus',q:'“노래가 끝나기 직전,<br>그 눈빛을 골랐다.”',chips:['2.4 SEC','CLOSE-UP','SAVE'],img:'A_045.png'},
 {t:'PERSON LOCK',sub:'IDENTITY',c:'#ff5eaa',d:'여러 장면 속 인물이 같은 사람인지 연결하는 핵심 레이어입니다.',m:'Identity match 98.6%<br>Face route A · consent required',q:'“다른 순간이어도<br>내가 좋아한 한 사람.”',chips:['PERSON','LOCKED','ROUTE A'],img:'A_090.png'},
 {t:'OUTFIT MAP',sub:'COSTUME',c:'#ffb35e',d:'영상 속 의상과 스타일을 하나의 360° 피규어 룩으로 묶습니다.',m:'Black crystal stage suit<br>8-angle turnaround complete',q:'“그날의 무대 의상까지<br>그대로 간직한다.”',chips:['OUTFIT','8 VIEWS','STAGE'],img:'A_135.png'},
 {t:'EMOTION',sub:'FEELING',c:'#fd6b7d',d:'표정과 음악, 사용자의 선택에서 이 순간의 감정 언어를 기록합니다.',m:'Awe 72 · Tenderness 61<br>Heartbeat marker +1',q:'“설명할 수 없어서<br>더 오래 남은 감정.”',chips:['AWE','TENDER','HEART'],img:'A_180.png'},
 {t:'MY NOTE',sub:'PERSONAL',c:'#d8a4ff',d:'팬이 직접 적은 문장이 기억을 개인적인 이야기로 바꿉니다.',m:'Saved Aug 09, 2026<br>Visibility · Only me',q:'“오늘의 나를 버티게 한<br>짧은 미소.”',chips:['NOTE','DATE','ONLY ME'],img:'A_225.png'},
 {t:'CONNECTION',sub:'NEXT PATH',c:'#59f0c0',d:'이 순간이 다음 영상과 이어지는 이유를 보여주는 러브트리의 가지입니다.',m:'Next moment · Backstage smile<br>Route strength 84%',q:'“한 순간이<br>다음 순간을 열었다.”',chips:['NEXT','ROUTE','TREE'],img:'A_315.png'}];
const stack=document.getElementById('stack'),legend=document.getElementById('legend'),slider=document.getElementById('explode');let selected=0,drag=false,lx=0,ly=0,rx=-12,ry=-22,playing=false,timer;
data.forEach((x,i)=>{let l=document.createElement('div');l.className='layer'+(i===0?' active':'');l.style.cssText=`--i:${i};--c:${x.c}`;l.innerHTML=`<div class="layer-head"><span>0${i+1} · ${x.t}</span><span>${x.sub}</span></div><div class="layer-body"><div class="visual"><img src="assets/figures/${x.img}"></div><div class="data"><div class="big">${x.t.replace(' ','<br>')}</div><p>${x.d}</p><div class="bars">${[1,2,3,4,5].map(n=>`<i style="--n:${n}"></i>`).join('')}</div></div></div><span class="axis">Z / ${i+1}00</span>`;l.onclick=()=>select(i);stack.appendChild(l);let b=document.createElement('button');b.style.setProperty('--c',x.c);b.className=i===0?'active':'';b.innerHTML=`<i></i><b>0${i+1} ${x.t}</b><small>${x.sub}</small>`;b.onclick=()=>select(i);legend.appendChild(b)});
function select(i){selected=i;let x=data[i];document.querySelectorAll('.layer').forEach((e,n)=>{e.classList.toggle('active',n===i);e.classList.toggle('dim',n!==i&&slider.value>75)});document.querySelectorAll('.legend button').forEach((e,n)=>e.classList.toggle('active',n===i));document.getElementById('inspectTitle').textContent=x.t.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());document.getElementById('inspectDesc').textContent=x.d;document.getElementById('inspectNum').textContent='0'+(i+1);document.getElementById('inspectNum').style.color=x.c;document.getElementById('inspectCode').textContent=x.t+' / '+x.sub;document.getElementById('inspectMeta').innerHTML=x.m;document.getElementById('quote').innerHTML=x.q;document.getElementById('chips').innerHTML=x.chips.map(c=>`<span>${c}</span>`).join('')}
function setExplode(v){slider.value=v;document.documentElement.style.setProperty('--explode',v/100);document.querySelectorAll('.layer').forEach((e,n)=>e.classList.toggle('dim',n!==selected&&v>75))}slider.oninput=()=>setExplode(slider.value);document.getElementById('assemble').onclick=()=>setExplode(0);document.getElementById('explodeBtn').onclick=()=>setExplode(100);
const stage=document.getElementById('stage');stage.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;stage.setPointerCapture(e.pointerId)};stage.onpointermove=e=>{if(!drag)return;ry+=(e.clientX-lx)*.18;rx-=(e.clientY-ly)*.14;lx=e.clientX;ly=e.clientY;document.documentElement.style.setProperty('--rx',rx+'deg');document.documentElement.style.setProperty('--ry',ry+'deg')};stage.onpointerup=()=>drag=false;stage.addEventListener('wheel',e=>{e.preventDefault();setExplode(Math.max(0,Math.min(100,+slider.value+e.deltaY*.08)))},{passive:false});
document.getElementById('play').onclick=()=>{if(playing){clearInterval(timer);playing=false;document.getElementById('play').textContent='▶ PLAY THE MEMORY STORY';return}playing=true;setExplode(88);let i=0;select(0);document.getElementById('play').textContent='Ⅱ PAUSE STORY';document.getElementById('status').textContent='STORY PLAYING · SOURCE';document.getElementById('progress').style.width='14%';timer=setInterval(()=>{i++;if(i>=data.length){clearInterval(timer);playing=false;setTimeout(()=>setExplode(0),300);document.getElementById('status').textContent='MEMORY ASSEMBLED · ONE STORY';document.getElementById('progress').style.width='100%';document.getElementById('play').textContent='↻ REPLAY THE MEMORY STORY';return}select(i);document.getElementById('status').textContent='STORY PLAYING · '+data[i].t;document.getElementById('progress').style.width=((i+1)/data.length*100)+'%'},850)};select(0);
