
const scenes=[
 {k:'01-welcome.png',step:'MEET YOUR KEEPER · 01',title:'Every memory<br>needs a <em>keeper.</em>',desc:'안녕하세요, 나는 LUMI예요. 최애의 영상에서 마음이 움직인 순간을 찾아 하나의 러브트리로 이어드릴게요.',p:'BEGIN WITH LUMI →',s:'HOW IT WORKS',cap:'ORIGINAL LOVETREE CHARACTER<br>MEMORY GARDENER · LUMI',card:`<div class="card-title"><span>WELCOME TO YOUR MEMORY GARDEN</span><span>01 / 06</span></div><div style="font-family:Georgia,serif;font-size:30px;margin-top:35px">One video.<br>Ten looks.<br>One growing story.</div><p style="color:#b9afbe;font-size:11px;line-height:1.6">Upload a moment you love.<br>LUMI will guide the rest.</p>`},
 {k:'02-orb.png',step:'GIVE ME A MEMORY · 02',title:'Start with the<br><em>video you love.</em>',desc:'콘서트, 무대, 인터뷰, 직캠 중 하나를 올려주세요. 파일은 이 프로토타입 안에서만 미리보기 됩니다.',p:'CHOOSE A VIDEO',s:'USE SAMPLE',cap:'LOCAL PREVIEW · PRIVATE BY DEFAULT',card:`<div class="card-title"><span>MEMORY INPUT</span><span>02 / 06</span></div><div class="drop" id="drop"><div><b>＋</b><strong>DROP YOUR FAVORITE VIDEO</strong><br><small>MP4 · MOV · JPG · PNG</small></div></div><div id="fileName" style="font-size:9px;color:#d4c5d6;margin-top:12px">NO FILE SELECTED</div>`},
 {k:'03-scan.png',step:'READ THE MOMENTS · 03',title:'Let the feeling<br><em>come into focus.</em>',desc:'LUMI가 영상의 표정, 의상, 무대와 감정 포인트를 읽어 후보 장면을 만듭니다.',p:'SCAN THIS VIDEO',s:'VIEW CRITERIA',cap:'MOMENT SCAN · IDENTITY + OUTFIT + EMOTION',card:`<div class="card-title"><span>MOMENT SCAN</span><span>03 / 06</span></div><div class="scan-ring"><div class="scanline"></div><img src="assets/figures/A_000.png"></div><div class="meters"><div class="meter"><b>98%</b>IDENTITY</div><div class="meter"><b>10</b>LOOKS</div><div class="meter"><b>24</b>MOMENTS</div></div>`},
 {k:'04-cards.png',step:'CHOOSE THE LOOKS · 04',title:'Keep the versions<br><em>that moved you.</em>',desc:'영상 100개 속 모습 중 원하는 10개를 고르듯, 각기 다른 의상과 감정을 피규어 컬렉션으로 선택합니다.',p:'KEEP SELECTED 10',s:'SHUFFLE LOOKS',cap:'CURATE · OUTFIT COLLECTION',card:`<div class="card-title"><span>CHOOSE 10 LOOKS</span><span>04 / 06</span></div><div class="thumbs">${'ABCDEFGHIJ'.split('').map((x,i)=>`<div class="thumb ${i<5?'active':''}"><img src="assets/figures/${x}_000.png"></div>`).join('')}</div><p style="font-size:9px;color:#b9afbe">5 selected · click cards to curate your set</p>`},
 {k:'05-build.png',step:'BUILD THE FIGURE · 05',title:'Turn every look<br><em>into an orbit.</em>',desc:'선택한 모습마다 8방향 이미지를 연결해 돌려볼 수 있는 디지털 피규어로 구성합니다.',p:'BUILD 360° FIGURE',s:'PREVIEW ANGLES',cap:'8-ANGLE TURNAROUND · DIGITAL COLLECTIBLE',card:`<div class="card-title"><span>FIGURE BUILDER</span><span>05 / 06</span></div><div class="build-ring"><i></i><img id="buildFigure" src="assets/figures/A_000.png"></div><div style="display:flex;justify-content:space-between;font-size:8px;color:#c8bdcc"><span>000°</span><span>090°</span><span>180°</span><span>270°</span><span>360°</span></div>`},
 {k:'06-bloom.png',step:'WATCH IT BLOOM · 06',title:'Ten figures become<br><em>your LoveTree.</em>',desc:'저장한 순간과 피규어가 가지처럼 연결되어, 나만의 최애 아카이브가 자랍니다.',p:'ENTER MY LOVETREE →',s:'REPLAY JOURNEY',cap:'YOUR MOMENTS · YOUR FIGURES · YOUR TREE',card:`<div class="card-title"><span>MY LOVETREE</span><span>06 / 06</span></div><div class="tree"><div class="crown"></div><div class="branch b1"></div><div class="branch b2"></div><div class="trunk"></div></div><div class="memory-dots">${'<i></i>'.repeat(10)}</div><div style="text-align:center;font-family:Georgia,serif;font-size:18px;margin-top:8px">10 looks · 24 moments · 6 paths</div>`}
];
let current=0,timer,buildTimer;const world=document.getElementById('world'),keeper=document.getElementById('keeper'),card=document.getElementById('card');
scenes.forEach((x,i)=>{let n=document.createElement('div');n.className='node'+(i===0?' active':'');n.innerHTML=`<i></i><span>0${i+1} ${['WELCOME','UPLOAD','SCAN','CHOOSE','BUILD','BLOOM'][i]}</span>`;n.onclick=()=>show(i);document.getElementById('steps').appendChild(n)});
function show(i){clearInterval(buildTimer);current=(i+scenes.length)%scenes.length;let x=scenes[current];keeper.classList.add('out');setTimeout(()=>{keeper.src='assets/keeper/'+x.k;keeper.classList.remove('out')},180);world.dataset.scene=current;document.getElementById('step').textContent=x.step;document.getElementById('title').innerHTML=x.title;document.getElementById('desc').textContent=x.desc;document.getElementById('primary').textContent=x.p;document.getElementById('secondary').textContent=x.s;document.getElementById('caption').innerHTML=x.cap;card.innerHTML=x.card;document.querySelectorAll('.node').forEach((n,j)=>{n.classList.toggle('active',j===current);n.classList.toggle('done',j<current)});bindScene();if(current===4){let a=0;buildTimer=setInterval(()=>{a=(a+1)%8;let vals=[0,45,90,135,180,225,270,315];let f=document.getElementById('buildFigure');if(f)f.src=`assets/figures/A_${String(vals[a]).padStart(3,'0')}.png`},350)}}
function bindScene(){document.getElementById('primary').onclick=()=>{if(current===1)document.getElementById('file').click();else if(current<5)show(current+1);else location.href='01-memory-capsule.html'};document.getElementById('secondary').onclick=()=>current===5?show(0):show(Math.min(5,current+1));if(current===1){let d=document.getElementById('drop');d.onclick=()=>document.getElementById('file').click();d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();handleFile(e.dataTransfer.files[0])}}if(current===3)document.querySelectorAll('.thumb').forEach(t=>t.onclick=()=>t.classList.toggle('active'))}
function handleFile(f){if(!f)return;let n=document.getElementById('fileName');if(n)n.textContent='READY · '+f.name.toUpperCase();setTimeout(()=>show(2),500)}document.getElementById('file').onchange=e=>handleFile(e.target.files[0]);
document.getElementById('next').onclick=()=>show(current+1);document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('skip').onclick=()=>show(5);document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1)});let wheelLock=false;world.addEventListener('wheel',e=>{if(wheelLock)return;wheelLock=true;show(current+(e.deltaY>0?1:-1));setTimeout(()=>wheelLock=false,700)},{passive:true});document.getElementById('autoplay').onchange=e=>{clearInterval(timer);if(e.target.checked)timer=setInterval(()=>show(current+1),4200)};
const p=document.getElementById('particles');for(let i=0;i<42;i++){let s=document.createElement('i');s.className='particle';s.style.setProperty('--x',Math.random()*100+'%');s.style.setProperty('--t',(5+Math.random()*8)+'s');s.style.setProperty('--drift',(Math.random()*160-80)+'px');s.style.animationDelay=(-Math.random()*10)+'s';p.appendChild(s)}show(0);
